### PR TITLE
İt doesnt let me play any sort of versions and everything is in place…

### PR DESCRIPTION
**Pull request by Muratsoyler**
… with the runtime pack and the right folders in the right folders

Please help me!

### CODE REVIEW

**Comment by Malaska678** [comment]
Why create a pull request?

**Comment by Malaska678** [comment]
Hmmm

**Comment by Muratsoyler** [comment]
Oh wait i wasnt suppose to do that sorry :(

**Comment by Malaska678** [comment]
Oh ok

**Comment by khanhduytran0** [comment]
You should make an issue instead of modify issue template...

**Comment by Muratsoyler** [comment]
Sorry i relazied

**Comment by WesleyVanNeck** [comment]
@Muratsoyler doesnt work for you because you dont listen to set it up

**Comment by WesleyVanNeck** [comment]
and making useless spam

**Comment by Muratsoyler** [comment]
How do i not listen up? İ bet you do just innrupt people just to look cool and you might now a little bit of code but that doesnt make the fact that you could be copy pasting code and doing it well so it Works and what did i do so it doesnt work and i did everything

**Comment by WesleyVanNeck** [comment]
> How do i not listen up? İ bet you do just innrupt people just to look cool and you might now a little bit of code but that doesnt make the fact that you could be copy pasting code and doing it well so it Works and what did i do so it doesnt work and i did everything

nope i dont intrupt also i dont copy paste like you

**Comment by Muratsoyler** [comment]
Yeah i wasnt copy pasting but im sure you are

**Comment by WesleyVanNeck** [comment]
nope

**Comment by WesleyVanNeck** [comment]
i dont copy past

**Comment by Muratsoyler** [comment]
Saying nope doesnt save u

**Comment by Muratsoyler** [comment]
Prove it

**Comment by Muratsoyler** [comment]
Prove it

**Comment by Muratsoyler** [comment]
Prove it

**Comment by khanhduytran0** [comment]
Saying anything does not save this pull request.

**Comment by Muratsoyler** [comment]
A
prove it

**Comment by artdeell** [comment]
> How do i not listen up? İ bet you do just innrupt people just to look cool and you might now a little bit of code but that doesnt make the fact that you could be copy pasting code and doing it well so it Works and what did i do so it doesnt work and i did everything

you know that by copy-pasting you can't just create anything

**Comment by artdeell** [comment]
which once again says that you do not know anything about coding

**Comment by Muratsoyler** [comment]
İ know because i. Dont do it so i know how bad it would be

**Comment by artdeell** [comment]
> İ know because i. Dont do it so i know how bad it would be

So, don't say prove it if you do not know.

**Comment by Muratsoyler** [comment]
You know what can i prove my innocence and end this stupid fight

**Comment by artdeell** [comment]
> You know what can i prove my innocence and end this stupid fight

I can report you as 9 year  old kid on Discord and GitHub and you'll get banned.

**Comment by artdeell** [comment]
You want it?

**Comment by Muratsoyler** [comment]
Sure thing dude you think me as 9 and knowing how to copy paste even if you think i do

**Comment by WesleyVanNeck** [comment]
> İ know because i. Dont do it so i know how bad it would be

you get mad at someting i said while i said we explaind how launcher worked we explained it and you still dont get it and you started a fight you started blaming about copy pasting

**Comment by artdeell** [comment]
> Sure thing dude you think me as 9 and knowing how to copy paste even if you think i do

Lmao, you do, and i think that you can't type, you're just copypasting sentences from somewhere and compose weird and unreadable text.

**Comment by artdeell** [comment]
So shut mouth @Muratsoyler

**Comment by khanhduytran0** [comment]
> Prove it

He is proof for u https://github.com/AOF-Dev/MCinaBox/pull/567

**Comment by artdeell** [comment]
Yeah. Plain copypasting EVEN without knowledge of the programming language

**Comment by Muratsoyler** [comment]
Shut mouth?? What does that mean was that suppose to be "shut up" and you cant even talk you just think ur old and maybe you are but you sure dont know how to talk

**Comment by artdeell** [comment]
> Shut mouth?? What does that mean was that suppose to be "shut up" and you cant even talk you just think ur old and maybe you are but you sure dont know how to talk

It's called "meme phrase" if you did not know.
You should watch all episodes of bottom gear, kid.

**Comment by WesleyVanNeck** [comment]
i have my proof also https://github.com/LoyaltyMC/CustomNameplates it originaly was made by other dud that privetly used i got permision and rewrited it

**Comment by Muratsoyler** [comment]
Hi kid's how are u

**Comment by WesleyVanNeck** [comment]
> Hi kid's how are u

lmao am 18 so not a kid

**Comment by artdeell** [comment]
> Hi kid's how are u

Idk who should be okay, because the only kid here is you.

**Comment by Muratsoyler** [comment]
Prove it

**Comment by WesleyVanNeck** [comment]
there is anough evidence of be a kid one is your acting childish

**Comment by artdeell** [comment]
blocked him on discord

**Comment by artdeell** [comment]
finally, silence

**Comment by Muratsoyler** [comment]
Thanks

**Comment by artdeell** [comment]
> Thanks

You're welcome)

**Comment by Muratsoyler** [comment]
Thanks for the ban i love it

**Comment by Muratsoyler** [comment]
That doesnt mean i cant talk from here and your afraid to ban me in here i know it

**Comment by khanhduytran0** [comment]
To silent here
- Lock the pull
- or do something other

**Comment by WesleyVanNeck** [comment]
am gone lock this a s spam

**Comment by Muratsoyler** [comment]
İ can send another pull lol

**Pull request closed without merging**
