### PR TITLE
Added option to swap X and Y of (virtual) mouse

### PR DESCRIPTION
**Pull request by RaydanOMGr**
Added options to swap the X and Y of the virtual mouse, seperately for in-game and in-menu. Recently found a person that had issues with the X and Y axis of their physical mouse being swapped due to android not accounting for orientation (landscape or portrait mode) on some android 13 versions. Thought this would be a nice feature to have.

### CODE REVIEW

**Comment by RaydanOMGr** [comment]
If you are interested on more specific details about the issue with physical mice, check this https://github.com/moonlight-stream/moonlight-android/issues/1240
To toggle the x/y axis swapping on or off, check the control customization tab.

**Comment by PedrixzZ** [comment]
I tested it and the mouse was completely buggy, with the options activated.

**Comment by PedrixzZ** [comment]
The video is here showing what happens: https://drive.google.com/file/d/1Xy2bjJ8VUF7lZlaB3_6Jg1OrLebSpv0H/view?usp=drivesdk

**Comment by RaydanOMGr** [comment]
pretty buggy, will probably close pr for now

**Comment by RaydanOMGr** [comment]
Fixed bugs, should be merge-worthy now

**Comment by RaydanOMGr** [comment]
> The video is here showing what happens: https://drive.google.com/file/d/1Xy2bjJ8VUF7lZlaB3_6Jg1OrLebSpv0H/view?usp=drivesdk

The video is not public, can't view.

**Comment by Duppz29** [comment]
yeahh

**Pull request closed without merging**
