### PR TITLE
by SteveAlexM

### PR DESCRIPTION
**Pull request by SteveAlexM**

### CODE REVIEW

**Comment by InfiniXDerg** [comment]
Add iOS 5.1

**Comment by SteveAlexM** [comment]
IOS??

**Comment by NotAHero04** [comment]
> Add iOS 5.1

For iOS go to the iOS repo.

**Comment by Py10lolz** [comment]
Add Nokia 69 🥵🥵🥵 hottie.

**Comment by WesleyVanNeck** [comment]
Stop with fake pull request

**Pull request closed without merging**
