### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by khanhduytran0**

### CODE REVIEW

**Comment by OwzygZawg** [comment]
New updates?

**Comment by OwzygZawg** [comment]
Laste build

**Comment by animetechnoz** [comment]
Hell there in the launcher have no oftion to run and aternos server dosnot supporting the pojav Launcher

**Comment by WesleyVanNeck** [comment]
> Hell there in the launcher have no oftion to run and aternos server dosnot supporting the pojav Launcher

Create a issue and don't use a pull request also that's fixed in the latest dev build

**Comment by khanhduytran0** [comment]
@animetoonshindi known issue

**Pull request merged**
