### PR TITLE
GL4ES: HOLY EDITION

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
# GL4ES: HOLY EDITION :stars:
Ladies and gentlemen, entities of the internet, TODAY we are here to celebrate the arrival of the one and only: GL4ES - HOLY EDITION !
"*Why ?*" I hear you ask ? Simple my child, simple really.

# Native 1.17+ support
Turns out that I could just apply some of my shader convertion tricks, such as:
- Avoid scalar type implicit conversion by making everything a float :gun:
- Add "**%**" operator support, by "just" getting both operands and making them go through a function
- Wrapping some functions and layout binding logic

Yes, this does require opengles 3.0 + to properly work. Older devices, if they can stomach those versions at all, will still require the patch.

# 1.7.10 crash fix
Oh yeah, [remember this issue from v3.3.1.1 ?](https://github.com/PojavLauncherTeam/PojavLauncher/issues/697)
Thanks to the blessing of this :angel:holy:angel: version, the crashing is no more.
*Also it was due to an issue with testing the sizeof() an int instead of a byte*

## Older versions QoL
Since older versions fare much better with openGL 1 (avoids crashes and "halved lighting" issues), some auto detection is added into the launcher to select the appropriate opengl version for you.
**Note:** I'm aware that some modded old versions cannot be detected.

## Miscenalleous
Less impressive changes, although noteworthy ones are:
- The profile migrator now avoid useless migrations, and takes into account the older vulkan based renderer
- Some devices were improperly reporting the display size, causing a control offset and slightly distorting minecraft, this has been fixed.
- Sometimes, the remove notch option was available despite the device being notchless.
- The CI is updated to avoid the gplay part being executed when a PR is made, to avoid the integration failing
- The CI is updated to use the latest gl4es :stars:HOLY:angel: edition instead
- The CI is updated not to use vgpu ever again.
- Removed the experimental fuckuries, there are kinda useless now.
- Hey, the build size has been trimmed as a result of less renderers !

### CODE REVIEW

**Comment by NotAHero04** [comment]
How holy

**Comment by kuzy21** [comment]
I KNEW IT ITZ HOLY HOLY HOLLYYY

**Comment by CriticalRange** [comment]
Holy moly macaroni

**Comment by kuzy21** [comment]
HOLLY I SAY HOLYYYYYY THE GODSSSS HAVVEVEVEV BLESSSS USSSSS SEE

**Comment by offbeat-stuff** [comment]
Does it mean performace improvements on gles 3.0

**Comment by TWTommyee** [comment]
Oh mai gawd

**Comment by offbeat-stuff** [comment]
Is it usable now??

**Comment by kuzy21** [comment]
It's broken guys

**Comment by kuzy21** [comment]
Everything looks weird

**Comment by BeJohnsonSentosa12** [comment]
> Is it usable now??

Yes, but it still can crash everytime so set hour auto save to 90s if it crash yours progress in your World not gone wrong

**Comment by WesleyVanNeck** [comment]
> > Is it usable now??
> 
> Yes, but it still can crash everytime so set hour auto save to 90s if it crash yours progress in your World not gone wrong

It's stable for me are you sure you using it

**Comment by WesleyVanNeck** [comment]
> It's broken guys

It's not broken

**Comment by CriticalRange** [comment]
> It's broken guys

I don't see any problem, maybe related to your device ?

**Comment by offbeat-stuff** [comment]
vanilla works but it does not to convert other shaders like from sodium

**Comment by offbeat-stuff** [comment]
> It's broken guys

You need opengles 3.0 to run the game perfectly

**Comment by WesleyVanNeck** [comment]
> vanilla works but it does not to convert other shaders like from sodium

use optifine optifine works

**Comment by WesleyVanNeck** [comment]
> > It's broken guys
> 
> You need opengles 3.0 to run the game perfectly

not really because optifine runs

**Comment by offbeat-stuff** [comment]
> > > It's broken guys
> > 
> > 
> > You need opengles 3.0 to run the game perfectly
> 
> not really because optifine runs

It is written in the pr description that you need opengles 3.2 to run the game perfectly otherwise you need the assets-v0 file

**Comment by WesleyVanNeck** [comment]
> > > > It's broken guys
> > > 
> > > 
> > > You need opengles 3.0 to run the game perfectly
> > 
> > 
> > not really because optifine runs
> 
> It is written in the pr description that you need opengles 3.2 to run the game perfectly otherwise you need the assets-v0 file

yes most phones have opengl es 3.2

**Comment by offbeat-stuff** [comment]
but not every phone has gles 3.2

**Comment by offbeat-stuff** [comment]
So would there be support for converting shaders loaded by sodium??

**Comment by TWTommyee** [comment]
Why you must use sodium? There's other excellent fabric optimization mods too, also even optifabtic works now

**Comment by offbeat-stuff** [comment]
Bro nothing comes close to what sodium does

**Comment by offbeat-stuff** [comment]
And sodium is the only rendering optimization mod on fabric, optifine is bloat.

**Comment by TWTommyee** [comment]
Starlight, entityculling, lithium, better fps mod and more, not only sodium

**Comment by offbeat-stuff** [comment]
they optimize game logic not the rendering

**Comment by offbeat-stuff** [comment]
I changed sodium shaders but it seems to get cut off after some code leading to ";" token expected error

**Comment by offbeat-stuff** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8472947/latestlog.txt)
Here is the log with the shader included

**Comment by offbeat-stuff** [comment]
I tried vanilla shader code, simple glShaderSource,
and the normal sodium
same error
tried to delete comments remove lines it just changed the line number of the error

**Pull request merged**
