### PR TITLE
LabyMod is not a hack client

### PR DESCRIPTION
**Pull request by LabyStudio**
LabyMod is not a hack client.
https://labymod.net

### CODE REVIEW

**Comment by artdeell** [comment]
LabyMod also is not a modloader though, idk how to classify it

**Comment by LabyStudio** [comment]
LabyMod is actually a modloader.
There is a whole wiki on how to create mods using the LabyMod api: https://wiki.labymod.net/pages/addon/
And there is also a website where you can download mods for LabyMod: https://flintmc.net/

So why is optifine listed as a modloader?

**Comment by xd100454** [comment]
I wish you could do a fix for labymod 4 to work on pojavlauncher. I love your client sooo much it's the best client also i bought some cosmetics to support your work <3333

**Comment by artdeell** [comment]
> LabyMod is actually a modloader. There is a whole wiki on how to create mods using the LabyMod api: https://wiki.labymod.net/pages/addon/ And there is also a website where you can download mods for LabyMod: https://flintmc.net/
> 
> So why is optifine listed as a modloader?

Because nobody has actually properly checked the readme since fairly long ago

**Comment by LabyStudio** [comment]
How about this one?

**Review by Mathias-Boulay — APPROVED** [review]

**Review by khanhduytran0 — APPROVED** [review]

**Pull request merged**
