### PR TITLE
vgpu

### PR DESCRIPTION
**Pull request by SolDev69**
Brings back vgpu, hey if zink got patched lets bring back all the old renderers :trollface:

### CODE REVIEW

**Comment by Bel69420** [comment]
Imagine, vgpu and virgl is got revive

**Comment by Vera-Firefly** [comment]
Meaningless update

**Comment by SolDev69** [comment]
This version has skill issue I'll fix later

**Comment by Vera-Firefly** [comment]
If you only want to add the vgpu renderer, you can just modify JREUtils,instead of jni

**Comment by Vera-Firefly** [comment]
All of the old renderers have been implemented on my side, so you don't have to bother yourself anymore.

**Comment by Vera-Firefly** [comment]
You can check https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink

**Pull request closed without merging**
