### PR TITLE
tried to fix grammar

### PR DESCRIPTION
**Pull request by ljcool2006**

### CODE REVIEW

**Comment by ljcool2006** [comment]
For some reason I am unable to edit the wiki. Would you mind giving me access to edit it?

**Comment by mchnjt** [comment]
We don't use the github-ish way for the wiki.

**Comment by ljcool2006** [comment]
> We don't use the github-ish way for the wiki.

Then how do I edit it?

**Comment by mchnjt** [comment]
You can open a pull request on [PLCommunity/PLCommunity.github.io](https://github.com/PLCommunity/plcommunity.github.io)
Note that this is an **unofficial wiki** since the official one, [PojavLauncherTeam/PojavLauncherTeam.github.io](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io) is archived. It might be back soon and we'll (aka @CriticalRange and me) consider to turn the unofficial one into an "more upstreamed" wiki and we'll push it's changes into the official one when it's open back again.

**Comment by Mathias-Boulay** [comment]
Since the branch had some changes, I manually applied the fixes that made the most sense. Thank you for the contribution

**Pull request closed without merging**
