### PR TITLE
remove discord button from main menu

### PR DESCRIPTION
**Pull request by rock3tsprocket**

### CODE REVIEW

**Comment by oodrand** [comment]
No

**Comment by ghost** [comment]
Why you want to remove discord button??

**Comment by rock3tsprocket** [comment]
> Why remove discord button??

the children that come into the server either begging for how to make pojavlauncher faster or for a free minecraft account

**Comment by artdeell** [comment]
1. No.
2. You have forgot to remove the string from strings.xml
3. Even if you fix that, still, no.

**Pull request closed without merging**
