### PR TITLE
Vertical fragment UI

### PR DESCRIPTION
**Pull request by artdeell**

### CODE REVIEW

**Comment by offbeat-stuff** [comment]
Can you please provide a description?
@artdeell

**Comment by offbeat-stuff** [comment]
just tried running this runs normal kind of

**Comment by offbeat-stuff** [comment]
Cant load 1.18.2 with this due to gl4es being broken but everything else is fine.

**Comment by WesleyVanNeck** [comment]
> Cant load 1.18.2 with this due to gl4es being broken but everything else is fine.

this about gui changes not render api

**Comment by zhong2707647607** [comment]
I have a SD Card, when I switch the storage part to SD card, the game can enter, but can not create an archive.

**Comment by offbeat-stuff** [comment]
just asking when is gl4es going to be fixed.

**Comment by offbeat-stuff** [comment]
I loaded a lower version and now mouse does not work. Can anyone send a version of pojav launcher that does work??

**Comment by SAPUTRAz8** [comment]
vertical-fragment-ui

**Review by dhddjdj — COMMENTED** [review]
vertical-fragment-ui

**Pull request closed without merging**
