### PR TITLE
Small UX improvements

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
**Features:**
- The ability to ignore the notch for android >= 9.0 with a new setting.
   - The notch become completely ignored, allowing for a more immersive experience.

**Fixes:**
- Fixed screen width detection, causing virtual buttons to be improperly placed
   - As a consequence, virtual hotbar keys are now properly positioned on top of the hotbar. 

**LIMITATIONS:**
- The fix doesn't work on either split screen or free form mode.

[With notch ignored](https://cdn.discordapp.com/attachments/749694761010724987/804764721193418802/Screenshot_20210129-181634.jpg)

[without notch ignored](https://cdn.discordapp.com/attachments/749694761010724987/804764721869619257/Screenshot_20210129-181728.jpg)

[Split screen mode](https://cdn.discordapp.com/attachments/749694761010724987/804732257473527808/Screenshot_20210129-151753.jpg)

[video of the setting](https://cdn.discordapp.com/attachments/749694761010724987/804765034004742144/TRIM_20210129_181425.mp4)

[video with the notch ignored](https://user-images.githubusercontent.com/24864674/106141756-e61fb080-6170-11eb-830b-66fe44240bab.mp4)

### CODE REVIEW

**Comment by artdeell** [comment]
Question: can notch ignore be disabled?

**Comment by artdeell** [comment]
Like, for example, some users (including me) may want the notch to create this black line because the notch is big

**Comment by Mathias-Boulay** [comment]
Nope, otherwise, the hotbar fix would be as wrongly placed as before for those devices. 😭

**Comment by artdeell** [comment]
Can you implement it even if the hotbar is misplaced?

**Comment by Mathias-Boulay** [comment]
I certainly can, just wait until I add commits into the pull request as usual 😅

**Comment by khanhduytran0** [comment]
[`WindowManager.getDefaultDisplay()` was deprecated since API 30](https://developer.android.com/reference/android/view/WindowManager#getDefaultDisplay())

**Comment by Mathias-Boulay** [comment]
> [`WindowManager.getDefaultDisplay()` was deprecated since API 30](https://developer.android.com/reference/android/view/WindowManager#getDefaultDisplay())

I'm aware of this, and the application is targeting API 29, making me unable to use this function without modifying the targeted API

**Comment by khanhduytran0** [comment]
But use `ctx.getDisplay()` will save few bytes 😅...
Also for target newer API in the future

**Comment by artdeell** [comment]
But
Can we get a switch even with the misplaced hotbar?

**Comment by Mathias-Boulay** [comment]
> But
> Can we get a switch even with the misplaced hotbar?

I'm checking that, it should be possible

**Comment by Mathias-Boulay** [comment]
I updated the original post to be more in line with the new features.
It should be ready to merge !(•̀ᴗ•́)و
If you have any question, please ask ! 😄

**Comment by Mathias-Boulay** [comment]
Just added a commit to clean up the UI for older android devices.
*Please tell me my pull request isn't being ignored* ヾ(･д･ヾ)

**Comment by WesleyVanNeck** [comment]
can this be merged

**Comment by Mathias-Boulay** [comment]
> can this be merged
Of course it can be merged !

**Comment by khanhduytran0** [comment]
My bad, `Context.getDisplay()` was only available since api 30.(?)

**Pull request merged**
