### PR TITLE
Update Gradle to 7.6.1 and prepare for Gradle 8.0

### PR DESCRIPTION
**Pull request by skbeh**
The only left blocker for Gradle 8.0 is that
task ':app_pojavlauncher:lintAnalyzeDebug' uses this output of task ':jre_lwjgl3glfw:jar' without declaring an explicit or implicit dependency.

### CODE REVIEW

**Comment by artdeell** [comment]
But did you test these changes on <1.13 mc? jre_lwjgl3glfw requires java 8 for its build.

**Comment by skbeh** [comment]
> jre_lwjgl3glfw requires java 8 for its build.

It should not matter since `targetCompatibility` in `jre_lwjgl3glfw/build.gradle` is set to `JavaVersion.VERSION_1_8`.

**Comment by artdeell** [comment]
> > jre_lwjgl3glfw requires java 8 for its build.
> 
> It should not matter since `targetCompatibility` in `jre_lwjgl3glfw/build.gradle` is set to `JavaVersion.VERSION_1_8`.

I said requires. Because if you build it with Java 8 compatibility but with a Java 9+ class library, it will break. Please test your PR on at least three major versions (1.19.4, 1.16.5 and 1.12.2) before submitting

**Comment by skbeh** [comment]
@artdeell Fixed.

**Comment by alfiancolab** [comment]
P

**Comment by Mathias-Boulay** [comment]
Tested the PR, it needs an additional fix for cross module compilation at different java versions on recent Android Studio versions. I'll merge the PR and push a fix at once.

**Pull request merged**
