### PR TITLE
vgpu opengl 3.0 support

### PR DESCRIPTION
**Pull request by WesleyVanNeck**

### CODE REVIEW

**Comment by dachisao** [comment]
hot

**Comment by CriticalRange** [comment]
Looks good

**Comment by Harpreet07king** [comment]
> _No description provided._

its showing that no news

**Comment by Harpreet07king** [comment]
please tall me how to fix to show news in pojav launcher

**Comment by WesleyVanNeck** [comment]
> please tall me how to fix to show news in pojav launcher

open issue dont tell issue that arnt vgpu related here

**Pull request merged**
