### PR TITLE
Make touch screen option enabled by default

### PR DESCRIPTION
**Pull request by asaldele1**
#3859

### CODE REVIEW

**Comment by GaucovyAero** [comment]
the issue is saying that the supposed feature does not work, because dragging in guis is not supported yet, does it work correctly for you?

**Comment by asaldele1** [comment]
Oh, it doesn't. But I think that it isn't bad if this feature will be turned on by default now

**Comment by asaldele1** [comment]
Also I found another function of this mode. You can click outside the inventory and it will be closed.

**Comment by asaldele1** [comment]
So what do you think?

**Comment by GaucovyAero** [comment]
people on discord say that enabling touchscreen controls makes pojav's hotbar buttons not work, i prefer it staying off and then anyone who wants it can enable it optionally, until maybe when it gets fixed

**Pull request closed without merging**
