### PR TITLE
This should fix a1.1.1 support

### PR DESCRIPTION
**Pull request by Moresteck**
Related to #1612

### CODE REVIEW

**Comment by Mathias-Boulay** [comment]
Maybe show us the alpha 1.1.1 working ? 👀 
Because the commit message doesn't inspire confidence 😂

**Comment by Moresteck** [comment]
Sorry, but getting Pojav to compile already took too much time, I won't try to test it any further.

**Comment by khanhduytran0** [comment]
> Sorry, but getting Pojav to compile already took too much time, I won't try to test it any further.

~~you can just enable GitHub Actions in your fork then...~~

**Comment by Mathias-Boulay** [comment]
Applying the fix locally, the a1.1.1 is still stuck to the mojang screen

**Comment by Moresteck** [comment]
What's the crashlog now? It must be something different than before, as I've patched the last one.

**Comment by Mathias-Boulay** [comment]
> What's the crashlog now? It must be something different than before, as I've patched the last one.

It didn't crash, it just softlocked 🤔

**Comment by Mathias-Boulay** [comment]
A few things are missing, but this PR is a working base for a1.1.1 support, I'll merge it.
Thanks for your contribution 😄

**Comment by winnerscdik** [comment]
wow alpha suprot!!!!1!1!!1

**Pull request merged**
