### PR TITLE
merge asap

### PR DESCRIPTION
**Pull request by mchnjt**

### CODE REVIEW

**Comment by GoneSubject** [comment]
cool

**Comment by dachisao** [comment]
what is this

**Comment by GoneSubject** [comment]
idk

**Comment by GoneSubject** [comment]
but i like the newest commit in here it's kinda cool

**Comment by GoneSubject** [comment]
what ._,

**Comment by bendolcok** [comment]
gh pr checkout 2310

**Review by bendolcok — COMMENTED** [review]
rscDoesMoreTrolling:patch-3

**Pull request merged**
