### PR TITLE
Request Merge Mesa22.1.2Zink

### PR DESCRIPTION
**Pull request by mcghjbcg**
Mesa23.0.4Zink MaliG715 device does not support requesting merge of Mesa22.1.2Zink

### CODE REVIEW

**Comment by Bel69420** [comment]
That could break version 1.12.2

**Comment by Bel69420** [comment]
If we update zink's mesa version

**Comment by mcghjbcg** [comment]
Just for unsupported devices

**Comment by mcghjbcg** [comment]
> If we update zink's mesa version

It should not be possible to update in a short period of time

**Comment by Bel69420** [comment]
Vulkan 1.3 should support zink but somehow it just broken for some reason

**Comment by Bel69420** [comment]
Only mali with Vulkan 1.1 are working

**Comment by Bel69420** [comment]
Like my device, Mali G77 MC9.

**Comment by Bel69420** [comment]
Gpu*

**Comment by Bel69420** [comment]
And also Adreno 6xx

**Pull request closed without merging**
