### PR TITLE
Changelog - Rev5 (for real)

### PR DESCRIPTION
**Pull request by mchnjt**
# PojavLauncher - Changelog Revision 5
This revision is specifically for iOS as requested by **khanhduytran0**.

This also refactors the entire code since the last cleanup done on rev4

## What's New
- A major change in terms of page design
- `index.html` now contains the same code—but with a special bottom bar
- (iOS) Now has it's own ~~changelog~~ news page
- Resolve an issue related to Google ~~hating patreon donations~~ hating any payment system other than GPlay Billing 
- ~~(Android) Now has a special bar on top (that stays, even if you scroll down(hopefully nothing breaks))~~
### Major change in page design
Remember that time in rev2 that i promised this will look better than the old one? Well, the community did praise me for it (rev4), but not the way i expected it to be.

I was thinking of something more stylish, like CSS effects, fonts, and stuff. But since im still a newbie in the HTML programming world, it would take "quite" some time in accomplishing these.

Thanks to `fonts.googleapis`, i was given myself the idea of "If i still can't, why not start with how the text looks like?"
### index.html
What's with the `<!-- TODO -->`?

You heard that right. Opening up [this repository's head gh-pages site](https://pojavlauncherteam.github.io/PojavLauncher/) gives you a blank page... right?

Not anymore!
### iOS's own page
rev4 did not look... quite fine, as the alternate word "unfitting" for iOS.
image0

To fight back against this, a revised pre-rev1 will be iOS's news page. With some new stuff too.
### Google hates Patreon?
IMG_20220923_111623

...blah blah blah.

A current workaround for this is to direct the user to a notice page rather than directing to the Patreon site itself.

~~google you should add payment for donations next time:likebhai:~~
### (new (and buggy that i had to consider if i should add it or scrap it)) header bar for Android
Can't really say anything about this right now but... i'll say the details later if it's a yay or nay.
### Work in Progress
IMG_20220922_215129
More screenshots will be added later.
### Scrapped Concept (early rev5.1/rev6)
- Why?
Knowledge. I don't understand full web JavaScript currently.
IMG_20220923_105337

## Q&A
- Why is this called `rev5`?
If you're confused about this:
`rev1` is #1715  , `rev2` is #1768, `rev3` is #2291 and `rev4` is #3410

- Why are `changelog.html` translations always getting a reset every revisions?
To ensure that **no specific languages has an outdated, buggy changelog** ~~and also to prevent questions like "WHY THE FUKK IS MY POJAV LAUNCHER DIFFERENT THAN OTHERS WTFFF"~~

**disclaimer: changelog page updates are not PojavLauncher updates.**
## What's Next
I'll be spending the rest of the days leaning full-stack web development for a while. 

I'm active on PojavLauncher Discord's offtopic too, so feel free to ask on what im currently doing there.

Also **i did say** i will finish this pr in an unspecified number of weeks, as time will tell if I would finish this pr in an expected date or in a delay for more days, might also take weeks.

### CODE REVIEW

**Comment by CasVeux** [comment]
Also for translators that spent half of a week translating this: im throwing your translations back at the trash again.

Due to my confusion regarding the real purpose of this webpage, i initially thought "oh this needs a huge revamp" but no.

This name of the button, which if you tap, or click (depending on your means) shows you this page, is "News".
The entirety of `changelog.html`, as i mentioned, will be thrown to `index.html`, which is where the rest of the scrapped stuff will go. I'll be using the Minecraft-Ten(copyrighted) font there aswell, since `index.html` isn't the shown webpage for both launchers.

**Comment by mchnjt** [comment]
A live demo is now available on https://veuxdesigns.github.io/WebTest/
Assume that this is still not final, so some stuff might change.

**Comment by mchnjt** [comment]
A scrapped feature from rev3 "Read More" has made it back to rev5 to cover/fix an issue regarding to long, boring text on the news section.

**Comment by mchnjt** [comment]
Old link `VeuxDesign` is no longer working.
Demo is migrated to https://duyware.github.io/CHTest/

**Comment by CriticalRange** [comment]
Hello @CasVeux,
I saw you used "because of" when you were mentioning about a positive thing:
Picsart_22-09-29_20-59-09-017
I believe "because of" is used for negative situations so if you'd use "thanks to" [or some sort](https://www.thesaurus.com/browse/thanks%20to) it could be better (:hyperrofel:).

**Comment by mchnjt** [comment]
There will be a two or three day delay with rev5. Just told you this as I'll be going out of the city.

Don't worry, I am still continuing rev5 locally.

**Comment by mchnjt** [comment]
Thanks for waiting everyone! I'll get into work shortly as i arrive home in a few hours.

**Comment by mchnjt** [comment]
Another update everyone! The testing repository for `rev5` is officially published to [a PojavLauncher organization oriented towards the community](https://github.com/PLCommunity/changelog)

This also gives anyone a chance in the community to fix any mistakes that i might make throughout the entire pull request.

As such, the new testing (preview) link is https://plcommunity.github.io/changelog/

iOS rev5 is almost done! I just need to rush

**Comment by mchnjt** [comment]
misclick

**Comment by mchnjt** [comment]
Anyways, iOS rev5 is almost done
I just need to rush over small cleanups

**Comment by CriticalRange** [comment]
@CasVeux instead of using a PNG for "Get it from Google Play", shall we use this? https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png as a link

**Comment by mchnjt** [comment]
> @CasVeux instead of using a PNG for "Get it from Google Play", shall we use this? https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png as a link

Working on it😄

**Comment by Mathias-Boulay** [comment]
Given some recent events, it would be in our common interest for this PR to be finished ASAP

**Comment by mchnjt** [comment]
Closing; this PR has been stalled for 2 months. I am also no longer working for it.

**Pull request closed without merging**
