### PR TITLE
[V.2.1] Controls update

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
# Intro
When the control v2 arrived, not everything could be fitted into the same PR, since time was a constraint and that many of the features were mature enough to go into mainline.

This said, smaller updates are more or less scheduled to come at random time intervals.
*(unless I'm paid, then I can dedicate time to bring a feature a client wants)*

## Full cross-device compatibility
*It was one of the missing features from the controls v2.*
The position of any ControlButton has been forcefully migrated to its dynamic equivalent.

- All screen aspect ratios are now supported, thanks to all dynamic positions being computed from the nearest borders of the screen instead of the top left.²
- Buttons now scale towards the center by default, instead of the bottom right.²
-  Buttons can now not be moved outside of the screen, avoiding accidental loss of buttons on the outside.

² Only concerns buttons with the automatic equations, not the user input ones.

## Context-aware snapping and alignment
Building a layout is frustratingly tedious, partially due to the inability to place buttons where we want.
This issue is now gone with auto snapping and alignment of buttons one to another.
This feature is also  *slightly* **context-aware**, which means a button can replace himself relatively to the button he snapped/aligned on !

## Miscellaneous :
- The new layout is in **NO SHAPE OR FORM** compatible with any previous versions of the controls, this is partially intended to force to move over the new scheme and take advantage of the new features when controls are shared.

- The dynamic position stuff is now hidden to the user by default. It can be toggled as easily as before for those who know how the system works. 

## What's left to do ?
- A message or something to tell the user his current layout isn't valid ?
- ~~Rename the "dynamic position" toggle to something a bit more fitting since all equations are dynamic under the hood.~~
- Surely something else.

## Images
2.1 controls at 100% scale:
2.1 controls at 100% scale

The same controls at 200% scale, you can see that buttons are still properly aligned.2.1 controls at 200% scale

[The controls in video](https://cdn.discordapp.com/attachments/867462167245619280/872170838500179998/20210803_193301.mp4)

### CODE REVIEW

**Comment by CriticalRange** [comment]
Very nice. I'm very happy about changes

**Comment by NotAHero04** [comment]
This will be the main advantage of PojavLauncher compared to other launchers.

**Comment by ghost** [comment]
I think this is bad

**Comment by WesleyVanNeck** [comment]
> I think this is bad

and who are you to say that? did you even try it?

**Comment by ghost** [comment]
@Mathias-Boulay you are making pojav no way to be compared with mcinabox the only thing pojav was lacking behind was controls of mcinabox was better than pojav but now u made it wayyyy better than mcinabox now pojav Launcher is the best 

Great job my favourite app developer

**Comment by Mathias-Boulay** [comment]
Closing, another grouped update will be done instead.

**Pull request closed without merging**
