### PR TITLE
Add Bahasa (Bahasa Indonesia) translation.

### PR DESCRIPTION
**Pull request by RadiatedExodus**
Several strings aren't translated (mainly the app name, MOTD, and the about). Ask me at Discord to translate them if you want however. (EthanPlayz#4533)

### CODE REVIEW

**Comment by RadiatedExodus** [comment]
Oh great I need to get another pull request again after this has been accepted to fix a typo...

**Comment by khanhduytran0** [comment]
You don't need create another pull request every new commits.

**Comment by khanhduytran0** [comment]
If not merged

**Comment by RadiatedExodus** [comment]
How do I modify the file?

**Pull request closed without merging**
