### PR TITLE
Upgrade zink vulkan to all versions fast

### PR DESCRIPTION
**Pull request by rishabha102010**
Please make it fast so game runs without capped fps

### CODE REVIEW

**Comment by rishabha102010** [comment]
Make all versions fast because the mid just caps the dps even though turning off allow vsync with zink

**Comment by rishabha102010** [comment]
Please make thank you

**Comment by ghost** [comment]
Really needed

**Comment by rishabha102010** [comment]
Yes please🙂

**Comment by rishabha102010** [comment]
Ok please make it iam begging thank you

**Comment by rishabha102010** [comment]
One workflow awaiting approvel? What does it says?

**Comment by rishabha102010** [comment]
Ok I don't know what's going on in this workflow is this workflow playable or unplayable

**Comment by EpicLays** [comment]
> Please make it fast so game runs without capped fps

_How does changing a single word changes how the renderer works_

**Comment by rishabha102010** [comment]
What's the point

**Comment by rishabha102010** [comment]
In zink renderer

**Comment by Marshall2439** [comment]
Bruh wtf

**Comment by Marshall2439** [comment]
That's not how it works

**Comment by SaanMye** [comment]
Bro rejected Harvard for being too smart 😭

**Comment by DeveloperMikey** [comment]
2,572 commits? did he just rewrite the application or what is this

**Comment by CowSheep72** [comment]
Changing words does not equal good FPS. Learn how zink works.

**Comment by rishabha102010** [comment]
Ok bro sorry I though zink would run like gl4es sorry

**Comment by rishabha102010** [comment]
> Bro rejected Harvard for being too smart 😭

I don't tell anything like that if so sorry

**Pull request closed without merging**
