### PR TITLE
Remove the ability to download Minecraft on Local accounts.

### PR DESCRIPTION
**Pull request by Weather-OS**
This is related to https://github.com/PojavLauncherTeam/PojavLauncher/issues/4431, and I'm honestly quite shocked on how PoJav launcher for the longest time didn't fix this issue out, because it only took about 12 lines of code to fix this issue.

**Why is the Pull request necessary?** To comply with https://pojavlauncherteam.github.io/LOCAL-MODE.html, and to not face potential legal issues from Mojang.

Everything is tested and is verified to work.

TODO: Translation for other languages.

### CODE REVIEW

**Comment by Weather-OS** [comment]
Quick Preview
Testing environment: Waydroid
image

**Comment by aaaapai** [comment]
WOW, looks like I'll have to get another launcher to download Minecraft. Oh, wait, I don't have to do that. I just need to use the modified version.

**Comment by Weather-OS** [comment]
Fixed a few stuff.
Here's the new preview:
image

**Comment by Raidware** [comment]
> This is related to #4431, and I'm honestly quite shocked on how PoJav launcher for the longest time didn't fix this issue out, because it only took about 12 lines of code to fix this issue.
> 
> **Why is the Pull request necessary?** To comply with https://pojavlauncherteam.github.io/LOCAL-MODE.html, and to not face potential legal issues from Mojang.
> 
> Everything is tested and is verified to work.
> 
> TODO: Translation for other languages.

Shit code.

**Comment by Weather-OS** [comment]
> Shit code.

I'm sorry if you didn't prefer my commits. Is there anything I can do to improve it?

**Review by Algiuxs — APPROVED** [review]
Everything looks great.

**Comment by Raidware** [comment]
Why Do U want to remove local accounts PovajLauncher does NOT give support if u dint have premium account

**Comment by Weather-OS** [comment]
> Why Do U want to remove local accounts PovajLauncher does NOT give support if u dint have premium account

I’m not “removing” local accounts. I’m removing the ability for local accounts to download Minecraft as per my statement.
You can still play with a local account if a Minecraft version is already installed.

**Comment by ly-nxs** [comment]
Is this going to be merged? (hope so)

**Comment by ghost** [comment]
I don't have good feeling about adding this

**Comment by ly-nxs** [comment]
Why, on the site it claims you can't download Minecraft with a local account, and yet you still can, all this does is patch that.

**Comment by Winterofwishing** [comment]
bro i see alot of apps making a update just for one patch its not a big deal

**Comment by ghost** [comment]
> bro i see alot of apps making a update just for one patch its not a big deal

No i saying remove ability local account can download minecraft is little difficult for me and many players after 5 years. And i can't get minecraft account because xbox live . Crack servers will be useless after this update

**Comment by Winterofwishing** [comment]
im pretty sure you can just make a microsoft account then buy minecraft from its official website.

**Comment by ghost** [comment]
> im pretty sure you can just make a microsoft account then buy minecraft from its official website.

Not really I'm living in iran

**Comment by Winterofwishing** [comment]
> > im pretty sure you can just make a microsoft account then buy minecraft from its official website.
> 
> Not really I'm living in iran

i live in the usa and not iran so idk how microsoft stuff works there sadly

**Comment by Weather-OS** [comment]
> > im pretty sure you can just make a microsoft account then buy minecraft from its official website.
> 
> Not really I'm living in iran

Whilst that country is still under heavy sanctions, I do know for a fact that you can still obtain a legal copy of Minecraft, Java edition from there if you circumvent sanctions as a civilian.

**Comment by Raidware** [comment]
They can found bypass methods. So this is useless.

**Comment by kiokori-git** [comment]
> They can found bypass methods. So this is useless.

implementing this would make pojavlauncher fully legal, not useless
if they can bypass it, thats them, not us. we're not associated with them or anything

**Comment by Coolboy42-89** [comment]
Plz don't remove thissss

**Comment by Coolboy42-89** [comment]
Ability

**Comment by CowSheep72** [comment]
im in support of removing it

**Comment by ghost** [comment]
I'm in support of don't remove it

**Comment by Coolboy42-89** [comment]
Then what's the point of local accounts or even pojav if u can't play

**Comment by kasrarouhi** [comment]
No I can play with local account

**Comment by Coolboy42-89** [comment]
> im in support of removing it

Whyyyy

**Comment by CowSheep72** [comment]
> Then what's the point of local accounts or even pojav if u can't play

mostly for testing and stuff, when you dont wanna have to play on your microsoft account(or it can be used as an alt account to dupe on p2w cracked servers)

**Comment by kasrarouhi** [comment]
So this is bad

**Comment by ghost** [comment]
So local account will be useless after this update. Not good

**Comment by Coolboy42-89** [comment]
Dont do this please

**Comment by CowSheep72** [comment]
do it please

**Comment by CowSheep72** [comment]
> Dont do this please

please do it

**Comment by VenomousSteam81** [comment]
> Dont do this please

You don't own a Hot Pepper Serrano, so your opinion is invalid.

**Comment by crystall1nedev** [comment]
Looks good to me. This is something I've been requesting from the Android team for a while, but no one ever got to (read: was not alone in this either, many from the QC staff, Minecraft modding community, and even Duy himself at times were also displeased at the inaction.)

Will probably take heavy fire for doing this, but merging it in since I seem to be the only one (alongside you, brave developer) with the balls to prevent the project from getting yoinked off of GitHub by Microsoft.

**Comment by alexanderpowerplays** [comment]
> > Then what's the point of local accounts or even pojav if u can't play
> 
> mostly for testing and stuff, when you dont wanna have to play on your microsoft account(or it can be used as an alt account to dupe on p2w cracked servers)

local accounts CANNOT use multiplayer and i repeat CANNOT use multiplayer

ive tested and it gives the error as shown in the screenshot
Screenshot_20240802-225904

**Comment by crystall1nedev** [comment]
Local accounts can use multiplayer, as long as the server has online-mode set to false.

**Comment by CowSheep72** [comment]
yas finally

**Comment by Cartrigger** [comment]
Demo mode could be a feature for all people who are now stuck without minecraft

**Comment by crystall1nedev** [comment]
This is something that I suggested to the Android team back when we first implemented local mode (read: before it was removed in a refactor of the code without prior notice to anyone else.)

The iOS side already has it implemented, it's a simple `--demo` flag and I whipped it up in a few hours by making a check for whether or not a user's Microsoft account owns the game. If players don't own it, then the demo flag is added, and they can play the game as it was intended. Another change was also that demo mode game files are inaccessible to local mode accounts, it's in a hidden location that can't be edited with normal tooling.

Local mode is also still available in both iOS and Android, the only difference is that local mode can't download Minecraft anymore. This is why it was renamed from offline to local mode.

**Comment by crystall1nedev** [comment]
The approach that the iOS side takes to the premium-demo-local situation is as follows, and it is exactly what I outlined in private developer chats (and I think even some public spaces) over a year ago now:

- Microsoft accounts that own the game
  - They have full access to everything
- Microsoft accounts that don't own the game
  - Game files are restricted to a hidden location that is not readily available to copy from.
  - Minecraft's built-in `--demo` flag is enforced on all sessions.
    - Some old versions of Minecraft don't have demo mode, so users get to play the entire game without limits there.
- Local accounts
  - They use the storage location that Microsoft accounts use.
  - They are able to launch and play Minecraft without limits.
  - They are **unable** to download Minecraft **using** PojavLauncher.

**Comment by Samalando** [comment]
This is a great thing to get added, and to all the haters, piracy is ILLEGAL meaning you could get fined or go to prison for doing it. Normal Minecraft is not "premium" as there is no official "non-premium" Minecraft. Great thing again, good job weather!

**Comment by Weather-OS** [comment]
@crystall1nedev Why was the commit reverted? Is another patch in the works?

**Comment by crystall1nedev** [comment]
I didn't revert it, that PR was in reference to me trying to re-add it after artDev did. See #development in our Discord.

**Comment by Weather-OS** [comment]
> I didn't revert it, that PR was in reference to me trying to re-add it after artDev did. See #development in our Discord.

Acknowledged. Anyways, thank you and anyone involved for shedding some light on this.

**Comment by alexanderpowerplays** [comment]
> This is a great thing to get added, and to all the haters, piracy is ILLEGAL meaning you could get fined or go to prison for doing it. Normal Minecraft is not "premium" as there is no official "non-premium" Minecraft. Great thing again, good job weather!

"piracy iS iLlEgAl" womp womp, ill keep pirating stuff till the end of time

**Comment by alexanderpowerplays** [comment]
this is why i now refuse to update pojav

simple as that bucko

**Comment by Samalando** [comment]
So then the update should be forced

**Comment by Samalando** [comment]
Something that's even more simple? Buying the game

**Comment by frdude** [comment]
And how exactly is it going to be enforced? now that they have the knowledge NOT to update, and you can't just edit stuff directly on their phone to "force update" the old version.

**Comment by Samalando** [comment]
I've seen things that require updates to work

**Comment by frdude** [comment]
> I've seen things that require updates to work

Yes, those exist, but it has to first be implemented into the current version. Which I don't believe exists in pojav.

**Comment by khanhduytran0** [comment]
@frdude it’s simple as to drop technical support for all old versions. We’ve been providing technical support to legit players only on our Discord server, but we have to admit GitHub issue is the backdoor to get support without a paid account. Requiring latest & official version will do.

**Comment by frdude** [comment]
> @frdude it’s simple as to drop technical support for all old versions. We’ve been providing technical support to legit players only on our Discord server, but we have to admit GitHub issue is the backdoor to get support without a paid account. Requiring latest & official version will do.

I mean this wouldn't make much of a difference, would it? People who didn't pay can't get support from the server anyway.

**Comment by ghost** [comment]
> > @frdude it’s simple as to drop technical support for all old versions. We’ve been providing technical support to legit players only on our Discord server, but we have to admit GitHub issue is the backdoor to get support without a paid account. Requiring latest & official version will do.
> 
> I mean this wouldn't make much of a difference, would it? People who didn't pay can't get support from the server anyway.

It's add for not face potential legal issues from Mojang. I don't know after 5 years pojav get legal issue from Mojang?! But it's not that necessary to remove this ability because local account make many places. I will play pojav glow worm

**Comment by kasrarouhi** [comment]
> > > @frdude it’s simple as to drop technical support for all old versions. We’ve been providing technical support to legit players only on our Discord server, but we have to admit GitHub issue is the backdoor to get support without a paid account. Requiring latest & official version will do.
> > 
> > 
> > I mean this wouldn't make much of a difference, would it? People who didn't pay can't get support from the server anyway.
> 
> It's add for not face potential legal issues from Mojang. I don't know after 5 years pojav get legal issue from Mojang

> > > @frdude it’s simple as to drop technical support for all old versions. We’ve been providing technical support to legit players only on our Discord server, but we have to admit GitHub issue is the backdoor to get support without a paid account. Requiring latest & official version will do.
> > 
> > 
> > I mean this wouldn't make much of a difference, would it? People who didn't pay can't get support from the server anyway.
> 
> It's add for not face potential legal issues from Mojang. I don't know after 5 years pojav get legal issue from Mojang?! But it's not that necessary to remove this ability because local account is going many places

**Comment by frdude** [comment]
Yeah, like I said before, nothing's stopping people from using a fork/a modified version of the launcher.


> > > @frdude it’s simple as to drop technical support for all old versions. We’ve been providing technical support to legit players only on our Discord server, but we have to admit GitHub issue is the backdoor to get support without a paid account. Requiring latest & official version will do.
> > 
> > 
> > I mean this wouldn't make much of a difference, would it? People who didn't pay can't get support from the server anyway.
> 
> It's add for not face potential legal issues from Mojang. I don't know after 5 years pojav get legal issue from Mojang?! But it's not that necessary to remove this ability because local account make many places. I will play pojav glow worm

**Comment by Coolboy42-89** [comment]
> > > Then what's the point of local accounts or even pojav if u can't play
> > 
> > 
> > mostly for testing and stuff, when you dont wanna have to play on your microsoft account(or it can be used as an alt account to dupe on p2w cracked servers)
> 
> local accounts CANNOT use multiplayer and i repeat CANNOT use multiplayer
> 
> ive tested and it gives the error as shown in the screenshot Screenshot_20240802-225904

They do use multiplayer use a username that no one has

**Comment by Coolboy42-89** [comment]
Well maybe we will not download the latest update

**Comment by ghost** [comment]
Or use forked version of pojav

**Comment by eebssk1** [comment]
if it's too trouble for those who want free play to rebuilt the software, just write a xposed module to override the check code.(There's user mode implementation for xposed so it's possible.)

**Comment by Greymagic27** [comment]
My only comment to reading all of this is that Minecraft is a paid game. Obtaining it free in any way is piracy, and therefore illegal.

I'm glad pojav made this change to comply with laws and Mojang policy.

As a sidenote, premium accounts haven't existed for over 10 years. There's no such thing anymore as a 'premium' account. You either own the game or you don't.

**Comment by artdeell** [comment]
Checked your github, bro is straight up resentful to this stuff. Prolly lives in the US or other extremely wealthy place, too.

**Comment by Greymagic27** [comment]
Moi? I don't know what about my github you saw to indicate that but ok.

Yes, I dislike piracy because it's illegal. But that's normal, no? 
I'm just glad you can no longer pirate the game (hopefully) using pojav.

**Comment by artdeell** [comment]
> Moi? I don't know what about my github you saw to indicate that but ok.

https://github.com/Greymagic27/Minecraft-Database/blob/main/GitHub%20Formatting/pirated-launcher.md
Quote:
> All “cracked”, or “non premium” launchers are illegal, and will steal your information

which is literal slander, as not all of the launchers steal your data (only the ones you list do)

> Yes, I dislike piracy because it's illegal. But that's normal, no? 

Do you, perchance, also pay for an Adobe Creative Cloud subscription?

**Comment by Greymagic27** [comment]
Oh, right. That's a repo for support stuff and it's not been used for months and months now. It's just a collection of info.

I mean any cracked launchers you should not be trusting. Anything cracked is most likely bad.

I don't pay for adobe cloud, no. I like the indication that I could be rich though. I will take that.

**Comment by Idkwoeer** [comment]
> My only comment to reading all of this is that Minecraft is a paid game. Obtaining it free in any way is piracy, and therefore illegal.
> 
> I'm glad pojav made this change to comply with laws and Mojang policy.
> 
> As a sidenote, premium accounts haven't existed for over 10 years. There's no such thing anymore as a 'premium' account. You either own the game or you don't.

You are the biggest clown I heard in my entire 16 years of existence

**Comment by Greymagic27** [comment]
For not liking piracy or people obtaining paid software illegally? Ok.

**Comment by ghost** [comment]
> Oh, right. That's a repo for support stuff and it's not been used for months and months now. It's just a collection of info.
> 
> I mean any cracked launchers you should not be trusting. Anything cracked is most likely bad.
> 
> I don't pay for adobe cloud, no. I like the indication that I could be rich though. I will take that.

So why old version of pojav or forked version of it not spyware or not have virus (I antivirus it)
Plus tlauncher is not spyware. You need to download it in official website and after that antivirus it in every update to sure but didn't virus detect

**Comment by Greymagic27** [comment]
Last reply I'll post here because it's getting off topic, but TLauncher is a bit of pirated software and has been proved to be spyware a few times. See these videos: https://www.youtube.com/results?search_query=tlauncher+spyware

Just because an AV doesn't detect it doesn't mean it's a legit bit of software. A lot of malware will add an exception to windows defender or whatever AV you have installed so it's not detected when it runs. TLauncher is 100% malware and will steal your account info. It's what you get for playing the game illegaly I guess :shrug:

**Comment by ghost** [comment]
So why my friend account not hacked and tlauncher doesn't seem run in background (I asked my friend). Don't trust all the YouTube video is for getting view. I see drama video is getting better views than other videos

**Comment by CowSheep72** [comment]
> My only comment to reading all of this is that Minecraft is a paid game. Obtaining it free in any way is piracy, and therefore illegal.
> 
> I'm glad pojav made this change to comply with laws and Mojang policy.
> 
> As a sidenote, premium accounts haven't existed for over 10 years. There's no such thing anymore as a 'premium' account. You either own the game or you don't.

uh even though i have an account, i've mostly changed my mind, im not really that supportive of the update anymore, local accounts should probably be kept as plugins for pojav

**Comment by CowSheep72** [comment]
bear in mind a lot of minecraft players are cracked players and do not have the money to buy the game/live in countries with sanctions, even i used to play cracked before buying a minecraft account.

**Comment by CowSheep72** [comment]
> Last reply I'll post here because it's getting off topic, but TLauncher is a bit of pirated software and has been proved to be spyware a few times. See these videos: https://www.youtube.com/results?search_query=tlauncher+spyware
> 
> Just because an AV doesn't detect it doesn't mean it's a legit bit of software. A lot of malware will add an exception to windows defender or whatever AV you have installed so it's not detected when it runs. TLauncher is 100% malware and will steal your account info. It's what you get for playing the game illegaly I guess 🤷

this is true however, do not use tlauncher

**Comment by ghost** [comment]
> > uh even though i have an account, i've mostly changed my mind, im not really that supportive of the update anymore, local accounts should probably be kept as plugins for pojav

Finally

> > Last reply I'll post here because it's getting off topic, but TLauncher is a bit of pirated software and has been proved to be spyware a few times. See these videos: https://www.youtube.com/results?search_query=tlauncher+spyware
> > Just because an AV doesn't detect it doesn't mean it's a legit bit of software. A lot of malware will add an exception to windows defender or whatever AV you have installed so it's not detected when it runs. TLauncher is 100% malware and will steal your account info. It's what you get for playing the game illegaly I guess 🤷
> 
> this is true however, do not use tlauncher

Hhhuhhh ok I report my friend about it but tlauncher isn't really a virus I promise

**Comment by CowSheep72** [comment]
i still don't like the pojav android fanbase though, especially unverified people, that's why i still somewhat support it

**Comment by CowSheep72** [comment]
i am also still in support of local mode download ability being removed too

**Comment by CowSheep72** [comment]
@kasrarouhi @Raidware my advice for yall is to eventually aim to buy a mc account, if limited by sanctions use a vpn.

**Comment by CowSheep72** [comment]
> > > uh even though i have an account, i've mostly changed my mind, im not really that supportive of the update anymore, local accounts should probably be kept as plugins for pojav
> 
> Finally
> 
> > > Last reply I'll post here because it's getting off topic, but TLauncher is a bit of pirated software and has been proved to be spyware a few times. See these videos: https://www.youtube.com/results?search_query=tlauncher+spyware
> > > Just because an AV doesn't detect it doesn't mean it's a legit bit of software. A lot of malware will add an exception to windows defender or whatever AV you have installed so it's not detected when it runs. TLauncher is 100% malware and will steal your account info. It's what you get for playing the game illegaly I guess 🤷
> > 
> > 
> > this is true however, do not use tlauncher
> 
> Hhhuhhh ok I report my friend about it but tlauncher isn't really a virus I promise

it is a spyware, plus the creators are very fucking sketchy, being political in response to spyware allegations, stealing the name of another launcher, and suing a terraria launcher

**Comment by ghost** [comment]
> @kasrarouhi @Raidware my advice for yall is to eventually aim to buy a mc account, if limited by sanctions use a vpn.

In my hole life I'm a f2p player at all and I don't buy anything related to app or game

**Pull request merged**
