### PR TITLE
add pl translation

### PR DESCRIPTION
**Pull request by maksw2**
add proper pl translation

### CODE REVIEW

**Comment by Algiuxs** [comment]
Use [crowdin](https://crowdin.com/project/pojavlauncher), it's a platform for translators, pojavlauncher uses this.

**Comment by kasrarouhi** [comment]
Pojav launcher need this update. Not all word translation lie this

**Comment by maksw2** [comment]
i translated on there, downloaded the xml file and made a pull request

**Comment by TarikBR** [comment]
> i translated on there, downloaded the xml file and made a pull request

This will be rejected, the only correct way to translate is with crowdin

**Pull request closed without merging**
