### PR TITLE
Get gl4es artifact

### PR DESCRIPTION
**Pull request by Google61**

### CODE REVIEW

**Comment by ghost** [comment]
你是中国人吗。
hi
你们的开源项目不错哦。

**Comment by kuzy21** [comment]
There is 3 main bugs with this release, 1. Enchanted amor from a distance looks weird on players, 2. When turn on 3d clouds it has a weird outline in them 3. Once you start to walk away from people there skin start to have a lag affect

**Comment by Mathias-Boulay** [comment]
@Google61 I'm not sure of what this thing exactly does

**Comment by Google61** [comment]
6 days later but whatever
@Mathias-Boulay Why rebuild gl4es every new commit _(thus doing the update commit)_, when you can simply download prebuilt library artifact from it's own repository at build time?
About local builds... add it as a submodule is enough?

**Comment by Mathias-Boulay** [comment]
I wouldn't be so sure about windows compatibility though

**Comment by Google61** [comment]
Windows compatibility [goes brrr](https://pojavlauncherteam.github.io/android/install-guide/building.html)

**Comment by lieasss** [comment]
hi

**Pull request closed without merging**
