### PR TITLE
Pojav launcher mouse

### PR DESCRIPTION
**Pull request by srobrine**
I like the way the mouse works in Pojav. can we take that mouse outside Minecraft?

### CODE REVIEW

**Comment by mchnjt** [comment]
> I like the way the mouse works in Pojav. can we take that mouse outside Minecraft?

Wanna do that? *You can root your phone!*

**Comment by Druxelite** [comment]
> > I like the way the mouse works in Pojav. can we take that mouse outside Minecraft?
> 
> Wanna do that? _You can root your phone!_

And get my phone fucking bricked? Hell nah

**Comment by WesleyVanNeck** [comment]
> > > I like the way the mouse works in Pojav. can we take that mouse outside Minecraft?
> > 
> > 
> > Wanna do that? _You can root your phone!_
> 
> And get my phone fucking bricked? Hell nah

funny you dont get it bricked by flashing twrp and then magisk over it it only happens when start flashing roms that arnt for your device

**Comment by WesleyVanNeck** [comment]
i never bricked my phone by rooting

**Pull request closed without merging**
