### PR TITLE
Made a sentence clearer

### PR DESCRIPTION
**Pull request by COZMIKDX**
Made some small changes to the first sentence under the The Launcher header to make it read better.

### CODE REVIEW

**Comment by Lunhatquoc** [comment]
:)

**Comment by mchnjt** [comment]
thanks for fixing our horrible grammar 👍

**Comment by COZMIKDX** [comment]
No problem!

**Comment by Mathias-Boulay** [comment]
Since the PR got conflicted, I applied some fixes manually. Thanks for your contribution

**Pull request closed without merging**
