### PR TITLE
Pojav Launcher Offline/Online accounts.

### PR DESCRIPTION
**Pull request by AndreiGamerYT-Oifficial**
Hello P. Launcher team! I am sorry for this request and i know why you removed the Offline account method but i just want to say that make something and add an option to play the betas/updates from GitHub. Please! Because right now i am playing the Google Play/old version. I want to try the new features. Me (and other players) can't buy Minecraft because personal info. Please do something! Thank you for understanding! :(

### CODE REVIEW

**Comment by CriticalRange** [comment]
> Hello P. Launcher team! I am sorry for this request and i know why you removed the Offline account method but i just want to say that make something and add an option to play the betas/updates from GitHub. Please! Because right now i am playing the Google Play/old version. I want to try the new features. Me (and other players) can't buy Minecraft because personal info. Please do something! Thank you for understanding! :(

Because personal info ? You mean nfa ?

**Comment by mchnjt** [comment]
> Hello P. Launcher team! I am sorry for this request and i know why you removed the Offline account method but i just want to say that make something and add an option to play the betas/updates from GitHub. Please! Because right now i am playing the Google Play/old version. I want to try the new features. Me (and other players) can't buy Minecraft because personal info. Please do something! Thank you for understanding! :(

what the fuck do you want us to do, implement tlauncher auth or write our own auth system? He'll nah we ain't doing that. We ain't riskin' shit

**Comment by AndreiGamerYT-Oifficial** [comment]
> > Hello P. Launcher team! I am sorry for this request and i know why you removed the Offline account method but i just want to say that make something and add an option to play the betas/updates from GitHub. Please! Because right now i am playing the Google Play/old version. I want to try the new features. Me (and other players) can't buy Minecraft because personal info. Please do something! Thank you for understanding! :(
> 
> Because personal info ? You mean nfa ?

nfa? What is that? And with personal informations  i mean something that we can't do or maybe don't have. For example money or card to pay them or an correct age to have money or card. Money doesn't grow on trees..

**Comment by KennyDevT** [comment]
Someone close this please

**Comment by AndreiGamerYT-Oifficial** [comment]
> Someone close this please



> Someone close this please

Why?

**Comment by KennyDevT** [comment]
Cause everyone is against the idea

**Comment by WesleyVanNeck** [comment]
> Cause everyone is against the idea

and this isnt a pull reqeast

**Comment by offbeat-stuff** [comment]
at least code it yourself if you want it
what even did you thought when you made this pull request

**Comment by Mathias-Boulay** [comment]
Get banned I guess

**Comment by vanistillhere** [comment]
the what

**Pull request closed without merging**
