### PR TITLE
extremely crucial bug fix

### PR DESCRIPTION
**Pull request by vinays6**
this has been bugging me for a long time

### CODE REVIEW

**Review by mchnjt — COMMENTED** [review]
where's the "crucial bug fix"

**Comment by vinays6** [comment]
In the commit

**Comment by mchnjt** [comment]
> In the commit

you literally changed nothing
Screenshot_20220629-230439

**Comment by vinays6** [comment]
It’s 1 line

**Comment by thegarykun** [comment]
"crucial bug fix"? seems to me that this is just a grammar correction :husk:

**Comment by Mathias-Boulay** [comment]
That's not a bugfix, but fine fine, I'll merge it.

**Pull request merged**
