### PR TITLE
Changelog: Upstreamed to Dahlia + a few changes [rev4]

### PR DESCRIPTION
**Pull request by mchnjt**
:frburn:
-TW Tommy

# PLauncher Changelog Update 220629
i'm back, with the same device fixed thrice.
(This PR supersedes #3316)

## What's New
- Upstreamed the `Changelog` contents to the latest release, "Dahlia".
- A new background (hopefully), leaving behind the launcher's color tone
- A few code cleanups, hopefully Syjalo won't bother me about it
- Temporarily removed "fancy tables ooooo" in the about section, then going to be replaced with text and pictures (unless i find an alternative to it)
- Now added "Guides" to the `changelog.html` file, hoping translators won't get confused about translating it (feature reusability pogg?1!1?1!1)
- Some cleanup on `gh-pages`' resource directories

### Upstreamed Changelog
Dahlia came out, and of course, i have to update the contents of it.
Also made a few grammatical fixes.

### New background
While exploring MCPi's resources, i found some....dirt.
Kinda reminds me on how this thing looks like before.
Screenshot_20220629-211131~2
(Used the darker one instead, the brighter one is literally the fucking block)

However, i can't just change it over my own decision.
I need the community to decide
(Now, if you're a mod and you're reading this, probably make an announcement please? Make them send out what background they want i guess)

### No more fancy tables?
- This is **temporary**

When i finished cleaning up `changelog.html`, i then put back the code containing these "fancy tables"
I thought it was a bug with my code editor at first (having Dahlia's changelog literally place wrong) until...

...yeah.
Apparently, "fancy tables" made the tabs into a stock image
(About tab is fine, others just won't show content)
#### Planned alternatives?
Planning on one right now.

### Guides
reusing the "Comment" feature of HTML i guess
Screenshot_20220629-205655~2
To translators: i hope this'll reduce your workload

### Translation Reset
All languages, with their respective changelog aren't upstreamed. Other users are still under the broken `v2` revision interface, so I would like to request a translation reset (@khanhduytran0 @Syjalo for the love of god pls reset the changelog translations)

To translators: your workload is reduced dw. Feel free to spam my dms on discord

## What's next after 220629?
This is **probably** my last pull request here, as soon I'll be starting to work on my personal projects.
But don't worry, I'll still watch over your issues regarding the changelog (like #2860) ~~Pssst. Don't forget to assign me over it devs. I can't scroll through thousands of "probably useless and spam" issues here~~

If i get the grip of time where i think "I'm done with all of my personal projects", then I'll get back into Project Infinity

Project Infinity (#3255) was supposed to be a pr where i test myself on the real challenge: improving the changelog's interface over my mental capability. I'll have to learn full HTML and CSS first for it of course.

While resources over the internet (i.e w3.css) are useful, Project Infinity is more than your "nah it's just a website embedded into the launcher"
More tabs, toggelable sidebar, idk embed the whole pojav wiki to it?

### CODE REVIEW

**Comment by mchnjt** [comment]
Screenshot_20220629-214301~2

**Comment by WesleyVanNeck** [comment]
i hope you didnt forget me

**Comment by mchnjt** [comment]
## ADDITIONAL CHANGES FOR THIS PR
- A png of "Repost to pay respects to Technoblade" will be added in the resource folder, and will likely stay there forever
- A remembrance for Technoblade will be shown, approximately for a month. [(source idea)](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/ab939970a0166b8bf04acfe3b2425eab1ba5d701)

>

**Comment by mchnjt** [comment]
While i still couldn't finish the `About` section (laziness + unmanaged plans), i'll probably sort out the resources directories.

**Comment by mchnjt** [comment]
> ## ADDITIONAL CHANGES FOR THIS PR
> * A png of "Repost to pay respects to Technoblade" will be added in the resource folder, and will likely stay there forever
> * A remembrance for Technoblade will be shown, approximately for a month. [(source idea)](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/ab939970a0166b8bf04acfe3b2425eab1ba5d701)
> 
> >

Image added. Credit goes to DLS or the original creator of the image.

**Comment by mchnjt** [comment]
## MORE CHANGES
- The epic return of the FAQ button.
Screenshot_20220709-164308

- New "Community" button (as shown above). What'll it contain? Secret.
- Different backgrounds per month, first feature from my planned "Project Infinity"
- A special background for June.
- Removed some unused code.

**Comment by mchnjt** [comment]
> ## MORE CHANGES
> ...
- About section, Credits section, and Patreon section has been merged, with additional content added
- New buttons hierarchy:
Screenshot_20220710-105004

**Comment by rsc4nevee** [comment]
## The following changes (in this pr) has been reverted due to code conflicts i made along the way
- Some cleanup on `gh-pages`' resource directories

**Comment by rsc4nevee** [comment]
*However, all files related to Technoblade is safe.

**Comment by mchnjt** [comment]
Oh, i kinda forgot to load the js file for the tabs. Fuck.
Revert cancelled. If you're seeing this via PojavLauncher Discord's webhook, please disregard the messages a while ago.

**Comment by mchnjt** [comment]
Ran out of ideas for the background.

**Comment by mchnjt** [comment]
Due to lack of time management, some changes expected from this PR will not be implemented until the next PR.

**Comment by mchnjt** [comment]
PR finishing shortly...

**Comment by mchnjt** [comment]
The next batch of commits will contain **85%** of this PR's progress so far. Though incomplete, i have to make it ready for review at a later hour due to
- I'm running out of time (i have something to do)
- It's been weeks since Dahlia's release, and the News Page didn't even change.

Don't worry about it though, I made it as appealing as possible.

As i said, **some changes expected from this PR will not be implemented until the next PR/Hotfix**. These include
- Seasonal backgrounds; dynamically changed every month still via a pull request
- Two tabs, namely "Community" and "FAQ"
- (unmentioned) Contributor's profile picture's appearance on the changelog 

Anyways, have a good day, and see you in the next pull request.

**Comment by mchnjt** [comment]
spam ping me on discord if something is broken lmfao

**Comment by mchnjt** [comment]
merge😭

**Comment by mchnjt** [comment]
merge eta

**Comment by Mathias-Boulay** [comment]
LGTM, aside from the commits naming 🤔 
I'll squash and merge the PR

**Pull request merged**
