### PR TITLE
Hotbar live resizing capability

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
**Features:**
- The hotbar is working with any GUI scale !
- It supports resizing in game !
- Supports illegal GUI settings (such as large on a 270p display)

**Fixes:**
- Fixed the hotbar size being wrongly computed when GUI scale was set to anything other than auto
- Fixed the hotbar size being wrongly computed when the resolution scaler was used.

**Miscellaneous:**
- The computeMcScale was refactored (and optimized) to getMcScale since it takes the stored scale into account now.
- You can now get a minecraft setting by the setting's name. Loads the mc settings if they have not been loaded yet.
- Works fine on split screen, should work on freeform as well.

**Limitations:**
- As for all McOptions related stuff, it only works with the new folder location, used since 3.3.1 😅 

**Videos:**
- [Working at 1080p](https://cdn.discordapp.com/attachments/749694761010724987/806632109069565953/TRIM_20210203_180250.mp4)
- [Working at 25% res from 1080p, with illegal GUI value stored in settings](https://cdn.discordapp.com/attachments/749694761010724987/806632177969528923/TRIM_20210203_215759.mp4)
- [Working in split screen mode, whatever the hell the resolution was](https://cdn.discordapp.com/attachments/749694761010724987/806632179307118602/TRIM_20210203_215713.mp4)

As usual, feel free to ask anything about this pull request !

### CODE REVIEW

**Review by WesleyVanNeck — APPROVED** [review]
looks good in my opinion

**Comment by Mathias-Boulay** [comment]
It still have small issues that have been reported by users

**Comment by WesleyVanNeck** [comment]
Looks like IT doesn't work @serpentspirale 

```
java.lang.NumberFormatException: s == null
	at java.lang.Integer.parseInt(Integer.java:577)
	at java.lang.Integer.parseInt(Integer.java:650)
	at net.kdt.pojavlaunch.BaseMainActivity.getMcScale(BaseMainActivity.java:1176)
	at net.kdt.pojavlaunch.BaseMainActivity$9.onSurfaceTextureAvailable(BaseMainActivity.java:669)
	at android.view.TextureView.getTextureLayer(TextureView.java:402)
	at android.view.TextureView.draw(TextureView.java:351)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8182)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Mathias-Boulay** [comment]
@LegacyGamerHD so you're the second one having this issue.
I'm freaking wondering why though as I could not reproduce the issue.

**Comment by WesleyVanNeck** [comment]
> @LegacyGamerHD so you're the second one having this issue.
> I'm freaking wondering why though as I could not reproduce the issue.

am reusing my old pojav folder

**Comment by WesleyVanNeck** [comment]
seems not the issue

**Comment by Mathias-Boulay** [comment]
> > @LegacyGamerHD so you're the second one having this issue.
> > I'm freaking wondering why though as I could not reproduce the issue.
> 
> am reusing my old pojav folder

Fuck that precisely the only use case that doesn't work.
*But doesn't the resolution scaler works only the new pojav folder ?*

**Comment by WesleyVanNeck** [comment]
> > > @LegacyGamerHD so you're the second one having this issue.
> > > I'm freaking wondering why though as I could not reproduce the issue.
> > 
> > 
> > am reusing my old pojav folder
> 
> Fuck that precisely the only use case that doesn't work.
> _But doesn't the resolution scaler works only the new pojav folder ?_

could it be am on android 11

**Comment by Mathias-Boulay** [comment]
no, since target API is set to 29, so compatibility mode applies.
Besides, you could not access any of the files if scoped storage was enforced

**Comment by WesleyVanNeck** [comment]
to bad it still hapens with fresh data

**Comment by Mathias-Boulay** [comment]
> to bad it still hapens with fresh data

*Oh my god why ?!*
I've tested this case by deleting the options file, I never crashed.
**The mystery gets thicker**

**Comment by Mathias-Boulay** [comment]
Edited main post to reflect limitations

**Review by khanhduytran0 — APPROVED** [review]

**Review by artdeell — APPROVED** [review]

**Pull request merged**
