### PR TITLE
Changelog Page Tweaks 2.1

### PR DESCRIPTION
**Pull request by mchnjt**
don't close :)

### CODE REVIEW

**Comment by rscDoesMoreTrolling** [comment]
closing for now :trollface:

**Comment by rscDMTalt** [comment]
Sheesh, i thought i didn't reopen this one

**Comment by mchnjt** [comment]
it's been 69 years 💀

**Comment by CriticalRange** [comment]
> it's been 69 years 💀

31 minutes
First reply
Will you do this again ?

**Comment by mchnjt** [comment]
idk :realtroll:

**Comment by CriticalRange** [comment]
> idk :realtroll:

Understandable :petrofel:

**Pull request closed without merging**
