### PR TITLE
Suggestions Adding New Renders

### PR DESCRIPTION
**Pull request by AnikyMX**
Can Pojav Launcher Add a New Renderer Named "OpenSWR"?
"The OpenSWR driver is a high performance, highly scalable software renderer targeted towards visualization workloads."
And Mesa Version 22.3.5 Already out.

More Info: https://www.mesa3d.org/

### CODE REVIEW

**Comment by GaucovyAero** [comment]
no software renderers please

**Comment by AnikyMX** [comment]
if so, how about just updating Mesa?

**Comment by demiswish** [comment]
> if so, how about just updating Mesa?

do it yourself buddy, you're literally in the source repo

**Comment by AnikyMX** [comment]
tutorials?

**Pull request closed without merging**
