### PR TITLE
Pojavlauncher pro

### PR DESCRIPTION
**Pull request by vasu1234321**
pojavlauncher  pro (new features )
 .exe installer 
Change pojav launcher full like Minecraft launcher 
And pojav launcher pro will be free*

### CODE REVIEW

**Comment by mchnjt** [comment]
> pojavlauncher pro (new features ) .exe installer Change pojav launcher full like Minecraft launcher And pojav launcher pro will be free*

can you shut the fuck up? PojavLauncherTeam and it's contributors is NOT part of Microsoft/Mojang Minecraft dev team. This app is not affiliated with any first party Minecraft producers.

**Comment by vasu1234321** [comment]
Just add. Exe installer
And change the interface.....

**Comment by mchnjt** [comment]
OH YOU THINK IT'S EASY? CODE IT YOURSELF

**Comment by vasu1234321** [comment]
iF u don't want to just wait for art dev Reply

**Comment by khanhduytran0** [comment]
> Just add. Exe installer

How so? Do we just get a Windows 11 ARM ISO and import to "PojavLauncher Pro"?

> And change the interface.....

Sure, by replacing offline account with local account.

**Comment by mchnjt** [comment]
> > Just add. Exe installer
> 
> How so? Do we just get a Windows 11 ARM ISO and import to "PojavLauncher Pro"?
> 
> > And change the interface.....
> 
> Sure, by replacing offline account with local account.

~~pirates like (maybe) him would be gone in March 10~~

**Comment by NotAHero04** [comment]
@vasu1234321 Let's break down your "feature request":
- .exe installer
Which OS does PojavLauncher run on? Which OS uses .exe extension for executables? 
- Change pojav launcher full like Minecraft launcher
Are you attempting to run Minecraft Dungeons?
- Pojav launcher pro will be free
PojavLauncher is always free.

**Comment by mchnjt** [comment]
hey don't forget about the artdev pron feature

**Comment by vasu1234321** [comment]
What is art dev pron

**Pull request closed without merging**
