### PR TITLE
About zink 

### PR DESCRIPTION
**Pull request by rishabha102010**
Ok let me tell clearly in zink i got 30 fps with shaders but still lags is zink opmises the shader? In old update if I reach 20 fps I get smooth experience without lag with shaders but in latest update experiencing lag even getting 30 fps with shaders make it playable even getting 30 fps with shaders it's not necessary but the zink opmises shaders getting 20 is enough for gameplay mak it please not necessary

### CODE REVIEW

**Comment by Marshall2439** [comment]
Wtf is bro yapping about?

**Comment by CowSheep72** [comment]
do you even know what you are talking about

**Comment by Marshall2439** [comment]
> do you even know what you are talking about

He Absolutely doesn't know what he is talking about

**Comment by Marshall2439** [comment]
...

**Pull request closed without merging**
