### PR TITLE
Added retry in AsyncMinecraftDownloader

### PR DESCRIPTION
**Pull request by qpowei**

### CODE REVIEW

**Comment by Mathias-Boulay** [comment]
This may be something useful, while I'm reviewing I noticed that you have 2 "update gl4es" commits that should not be there :eyes:

**Comment by artdeell** [comment]
also why write another method

**Comment by Mathias-Boulay** [comment]
> also why write another method

True, it could be integrated into the monitored download function.

**Comment by Mathias-Boulay** [comment]
Also, the PR just throws away the buffer recycling, which means we'll get wasted objects

**Comment by qpowei** [comment]
Thank you.I will improve them

**Comment by qpowei** [comment]
> 

Wait. *Buffer* is a buffer after all. The new data will overwrite the original buffer. The length of the new data will be returned by the *read* function, so you should not get wasted objects. (*Arrays.fill* in the new PR should be deleted.)

**Pull request closed without merging**
