### PR TITLE
Improvements on the bug report template

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
I made use of the markdown syntax to make titles a bit clearer.
I also added the requirement to attach a log file and where it is located.

This should hopefully avoid the usual request for the logfile.

### CODE REVIEW

**Comment by netkv** [comment]
also would be pretty nice to make people use atleast bit describing titles instead of just "[bug]" or "[error]"
do you think it would be good idea to add it to template?

**Comment by Mathias-Boulay** [comment]
Most of the time, people don't know what exactly their bug is, so I decided not to include it.
But I could add a statement about how a good title makes a faster bug fixing ?

**Comment by artdeell** [comment]
Yea, sure

**Comment by Mathias-Boulay** [comment]
I added an indirect incentive to fill the title, seemed better than telling directly to the user that he HAS to do a good title

**Pull request merged**
