### PR TITLE
Update Android.yml

### PR DESCRIPTION
**Pull request by AMDgamer150807**

### CODE REVIEW

**Comment by artdeell** [comment]
1. There's no branch "v3openjdk", there's `v3_openjdk`
2. By adding `v3_openjdk` to ignore list, you will completely disable feature builds
3. Changing "Set up JDK 1.8" to JDK 16 does not change the launcher java version, it only changes the Java VM used during the build process

**Comment by khanhduytran0** [comment]
Do you know what are you changing?
- Ignore building on Default **v3_openjdk** branch <ins>instead of</ins> **l10n_v3_openjdk** branch.
- Use Java 16 to </ins>build the APK</ins>. Building APK <ins>doesn't</ins> create a **Game Runtime** from **Builder java Runtime version**

**Comment by khanhduytran0** [comment]
understand what is different between **Game Runtime** and **Build Runtime** before pr bruh @AMDgamer150807

**Comment by AMDgamer150807** [comment]
thank you very much for telling me

**Pull request closed without merging**
