### PR TITLE
Improve user experience when logging in with Microsoft

### PR DESCRIPTION
**Pull request by zhufucdev**
Here's how the UI looks like:
Screenshot 2022-02-26 21 39 28

I'm also working on some optimizations for Chromebooks, which suffer from context losses when resizing free window

### CODE REVIEW

**Comment by artdeell** [comment]
Good idea, but:
- Action scripts were not yet reconfigured to work with new build tools, which will lead to action builds constantly failing
- There's a function and variable naming convention change going on, I recommend you to postpone the PR for now. For more info, [join our discord](https://discord.gg/invite/6RpEJda).

**Comment by zhufucdev** [comment]
> Good idea, but:
> 
> * Action scripts were not yet reconfigured to work with new build tools, which will lead to action builds constantly failing
> * There's a function and variable naming convention change going on, I recommend you to postpone the PR for now. For more info, [join our discord](https://discord.gg/invite/6RpEJda).

I see. Thanks for inviting, but I'm not quite available these days. Perhaps part of my work can be used while building the tidier code base. Hope this project will advance to the better.

Here are my other suggestions:
* Use common style, instead of declaring each explicitly.
* According to [Google's Guideline](https://developer.android.com/topic/arc/window-management#window_dimensions), adopt window size instead of screen size.
* Set background resource programmatically for MineButton.
* Abandon AsyncTask.
* Use a HTTP library, OKHttp for example, in MicrosoftAuthTask.

**Comment by Kdyedse** [comment]
Hay

**Comment by SAPUTRAz8** [comment]
zhufucdev:v3_openjdk

**Comment by SAPUTRAz8** [comment]
<meta-data android:name="WindowManagerPreference:FreeformWindowSize"
           android:value="[phone|tablet|maximize]" />
<meta-data android:name="WindowManagerPreference:FreeformWindowOrientation"
           android:value="[portrait|landscape]" />

**Comment by Mathias-Boulay** [comment]
Due to more or less drastic future changes in the internal of the launcher, including the authentication, this PR won't be merged.
Note @zhufucdev that some of your common sense suggestions have been implemented of the future changes

**Pull request closed without merging**
