### PR TITLE
[Windows] Fix Error Syntax languagelist_updater.bat

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
hard moment

**Comment by GoneSubject** [comment]
what is this

**Comment by ghost** [comment]
> what is this

ur mom

**Comment by GoneSubject** [comment]
ah ok ig

**Comment by ghost** [comment]
no new commit coz this issue very hard

(or i am stupid)

**Comment by GoneSubject** [comment]
> no new commit coz this issue very hard
> 
> (or i am stupid)

im more stupid bruh

**Comment by ghost** [comment]
> > no new commit coz this issue very hard
> > (or i am stupid)
> 
> im more stupid bruh

maybe ur mom more stupid

**Comment by GoneSubject** [comment]
> > > no new commit coz this issue very hard
> > > (or i am stupid)
> > 
> > 
> > im more stupid bruh
> 
> maybe ur mom more stupid

nah

**Comment by ghost** [comment]
No progress moment

**Comment by ghost** [comment]
Ah conflict

**Pull request closed without merging**
