### PR TITLE
Add Back VGPU Render

### PR DESCRIPTION
**Pull request by AnikyMX**
Add Back VGPU Rendering, Although There Are Devices That Don't Support And Can't 1.17+, But This Can Make Players With HP Lower Specifications Happy

### CODE REVIEW

**Comment by mchnjt** [comment]
whar

**Comment by mchnjt** [comment]
Also
- HGL4ES supports 1.17+ now. No more patches, just grab JRE17.
- Use OptiFine and lower the game resolution.
- ...the hell is `HP Lower Specifications` anyway?

**Comment by AnikyMX** [comment]
cellphones that have the Snapdragon 400 Series chipset, Mediatek A Series, etc

**Comment by mchnjt** [comment]
> cellphones that have the Snapdragon 400 Series chipset, Mediatek A Series, etc

No.

**Pull request closed without merging**
