### PR TITLE
Update stuff

### PR DESCRIPTION
**Pull request by mchnjt**
idk duy didnt want people to translate the js script into a fuckin idk some hacker's bullshit

### CODE REVIEW

**Comment by khanhduytran0** [comment]
~~inappropriate name moment~~

**Comment by mchnjt** [comment]
> ~inappropriate name moment~

nOoOo

**Comment by mchnjt** [comment]
this should be legal now :trollface:

**Review by saputra111 — COMMENTED** [review]
README.md

**Review by SAPUTRAZZ — COMMENTED** [review]
README.md

**Pull request merged**
