### PR TITLE
Update Android.yml

### PR DESCRIPTION
**Pull request by AMDgamer150807**

### CODE REVIEW

**Comment by khanhduytran0** [comment]
So why?

**Comment by AMDgamer150807** [comment]
Hahaha

**Comment by khanhduytran0** [comment]
Change then revert then PR, what do you want?

**Comment by khanhduytran0** [comment]
> Hahaha
> […](#)

I guess I will have to add you into block list.

**Comment by khanhduytran0** [comment]
It is not funny.

**Comment by AMDgamer150807** [comment]
Hmmmm
























ok

**Pull request closed without merging**
