### PR TITLE
The great refactor

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
# The Great Refactor
For the ones who ever took a dive into the codebase, you may have realized how messy the codebase is, mainly due to the inconsistency in both naming and code style.

This PR attempts at solving this issue by introducing both some code style and naming conventions, basing itself from a [handy premade guideline that I didn't have to redact](https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md)

## Changes highlights:
- Many, **MANY** variables have been renamed
- Some redundant blocks of code have been removed
- Scopes of some variables have been reduced
- Reduced the scope of Exception catching to avoid hiding underlying issue
- Reduced the number of instructions inside `try catch` blocks
- Reduced the number of deprecated functions being used
- Flattened out part of the code

## Notes:
Not all files were changed, for multiple reasons:
I may just have missed them when going through the files :sweat_smile:
I couldn't find a fitting name, and we have other matters to deal with.
Some parts of the code will be reworked/rewrote soon, making the refactoring pointless

Also some dialogs have the system theme for now 😅

### CODE REVIEW

**Comment by mchnjt** [comment]
REFACTORING THE PIRATES

**Comment by CriticalRange** [comment]
> REFACTORING THE PIRATES

REFACTORING THE CHILDREN

**Comment by mchnjt** [comment]
> > REFACTORING THE PIRATES
> 
> REFACTORING THE CHILDREN

REFACTORING THE ORPHANS

**Comment by CriticalRange** [comment]
> > > REFACTORING THE PIRATES
> > 
> > 
> > REFACTORING THE CHILDREN
> 
> REFACTORING THE ORPHANS

REFACTORING THE MICROSOFT

**Comment by CriticalRange** [comment]
Ok went a bit far there

**Pull request merged**
