### PR TITLE
New translations strings.xml (Chinese Simplified)

### PR DESCRIPTION
**Pull request by fengyec2**

### CODE REVIEW

**Comment by mchnjt** [comment]
though i like the pr number, i don't like the way you translated. Please use the repo/app's crowdin, not open pr for translation.

**Comment by fengyec2** [comment]
> 

I see. But Crowdin already has an updated Chinese translation, but it doesn't apply to Pojav.

**Comment by mchnjt** [comment]
iirc crowdin language changes are applied to dev builds, a.k.a action builds. They don't speed their way to playstore.

**Comment by fengyec2** [comment]
> iirc crowdin language changes are applied to dev builds, a.k.a action builds. They don't speed their way to playstore.

But i see New Crowdin updates failed

**Comment by KENCIKTUMAN** [comment]
> _ No description provided. _

**Comment by KENCIKTUMAN** [comment]
gh pr checkout 2629

**Review by KENCIKTUMAN — APPROVED** [review]

**Pull request closed without merging**
