### PR TITLE
CONTROLS V2 !

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
# The controls revamp update !
Finally, this update is ready ! I never thought it would take this long, but the more I try to use this app, the more unusable it seems to me.
So let's get into what I've been working on.

# First the touch controls
*\*screams*\* HOW THE FUCK DO YOU PLAY WITH THE CURRENT GARBAGE ?! 
Given the current usability, there are a lot of things to tackle here.

 ## Multi-keys support
 Any button can hold up to four keys. I can finally jump, shift, hide GUI and take a screenshot at the same time !
 As such, hold Alt/Ctrl/shift options are gone, since you can now send the key in one of the four slots.

 On a more serious note, it solves the issue with the current control scheme: it forces me to press both the forward and right button , if I want to go to the left and the right at the same time, which is quite an issue given the limited space, fingers we have.

## Increased visual customization
People wished for colored buttons, so here they are !
You can now configure many new button properties, such as: 
- The background color and transparency.
- Stroke color and size.
- Corner radius of buttons. You can now have fully rounded buttons !
- Background transparency --> Button transparency.

It goes without saying, those options are more here to answer ancient and current users of MCinaBox :eyes:

## Better toggling
When moving the camera around, toggling was previously impossible.
That's heresy ! So I fixed it. Feel free to toggle on and off a thousand times :smile:
**Note:** The current toggling system is incompatible with the next feature. 

## Swipeable buttons 
Yes, you heard it right. This long-time-requested feature is finally coming to PojavLauncher !
That's not a joystick, but it is better than nothing :partying_face:

Quick explanation on how it works:
 - If you press or slide into the button, it counts as a press.
 - If you remove your finger, either by sliding out or removing the finger from the screen entirely, it counts as an un-press.

Buttons can be set swipeable with a simple toggle in the custom controls menu.

## Key drawers
What **is** a key drawer, you might ask ?
Simple, it draws keys... Okay, this sounds dumb said like this.
It allows you to hide only some buttons behind another one.

This feature is originally intended for modpack players who need a lot of keys for all their mods, but it stroke me that some fuckers love to fill their *ENTIRE SCREEN* with buttons. 
You're going to love having access to so many buttons while taking minimal screen real estate :sparkles:

## Better Hotbar
This one is partly in the same vein as the **better toggling** update.
If you move the camera around, you couldn't FUCKING SWITCH ITEMS !
I can't express how this useless behavior was getting on my nerves when I needed to place torches in a cave.
That's also heresy. So I also fixed it.

I also fixed another peculiar behavior that was seemingly noticed by almost no one.
When sliding the finger on the hotbar then clicking somewhere, the camera would jump by the amount of px slid on the hotbar.

 ## Better cross-device layout compatibility
*I admit, this one is half a lie since the revamped controls aren't compatible with Apple devices (yet ?).*

 When you import a v1 keyboard layout to your device, you may have come across an unfortunate issue, the size is completely mismatched for your device !
 Well, fret not because the new layout scheme is resolution-independent!
 Meaning my beautiful keyboard for my 4k smartphone will properly fit on your crappy 720p device.

**Note:** It is not aspect ratio independent though, so I dunno how tablets users will experience this.

## THE CAMERA
OH MY GOD WAS THIS THING UNUSABLE !
THIS SOLE POINT IS WHAT MADE ME USE **MCinaBox** OVER THIS LAUNCHER THE WHOLE TIME !

This may have been one of your first impressions but the camera is *SLOOOOOOOOOOOOW*
This was due to two separate issues:
- We were losing MotionEvent data.
- The precision wasn't top-notch, sub-pixel movements were lost, causing small gestures to be ignored.

Both of these issues were fixed.
As a result, the camera is now butter smooth **and** sensitive to small gestures !

## Device-independent sensitivity
As you may have noticed, but the camera moved way faster on a 4k phone compared to a 720p one.
Since we used to get the difference of raw mouse coordinates and send them to Minecraft, sliding across a high resolution screen was accounting for way more pixels.

This has been solved.
Devices now all have the same sensitivity regardless of the screen resolution, providing a more unified experience across devices.
As such, the default sensitivity has been tweaked to **feel just right**.

### Memory 
With the introduction of the **key drawer**, the number of buttons to be stored in memory is anticipated to be thrice the current average.
*To account for this, the following optimizations were introduced:*
- Edit object instantiation on need only. Saves memory when not editing controls.
- Removed some useless variables from BaseMainActivity.

### CPU:
- Improvements in the branching system on the BaseMainActivity.

---
*Phew*
Touch controls are usable now, don't you think ?
But wait, there is M̸̢̱͙̉̋̀͠Ơ̵̙͐̽̅̈Ṛ̷̥̯̍́̔͂E̵̪̺̖̜̿̎̎̀̔ ! 

# Then Hardware keyboard controls
*Hey, but the keyboard works fine !*
Yes, but it doesn't mean it can't be improved upon.

### Memory:

- Reduced the size of the key converter table by using more primitive types.

### CPU:
Any player using a keyboard may have noticed it, but using a hardware keyboard doesn't come cheap for the device's CPU. Fortunately, I've brought some optimizations to the table.

- Looking up the key converter table is now slightly faster
- Reduced the number of lookups from 2 to 1, so twice as fast.
- Reduced the need to even do a lookup for 90+% of KeyEvents.

With all of this, the keyboard overhead has been heavily lowered and is between 3x to 5x faster in commons scenarios.

## New bugs
Due to an optimization, long pressing a key won't spam the key in any Textbox.
Sorry if you can't spam *tttttttttttttttttttttttttttt* in chat now :eyes:

# Don't forget Hardware mouse controls
*Yeah yeah, mouse controls are totally fine*
Here are some improvements nonetheless.

### CPU:
- Improved pointer lookup speed *ever so slightly*.
- Greatly improved event handling, fixing stutters when spamming with a mouse click.

With that, mouse lags should be gone *at least, I hope so*

*Phew*, we're done with hardware inputs.
**Or are we ?**

# GAMEPAD CONTROLS !
Introducing gamepad controls, something that I miss not having before.

## Great ! How does it work ?
- Connect your gamepad to your device.
- Play ! 

Yes, it is that simple.

## Features:
- Plug and Play. *-"it just works."*
- Low performance overhead.
- Works with any version of minecraft Pojav already work with.
- Supports menus properly.
- Dynamic pointer scaling with the GUI size and resolution scaler.
- *"Wide range of compatible gamepads."*

## Bugs
- Android has a fucked up mapping for certain devices, cannot be fixed.

# Miscellaneous
The section is more about technical details/additions made to the project for devs to take notice of.
So, lambda users may not have any interest in it.

**- BaseMainActivity:**
This activity has been cleaned up by as much as I could, why adding the revamped controls in.
Please, try not to trash this activity, as the feature set goes bigger.

**- DefocusableScrollView**
For the sake of the new button setting screen, I needed something that can ingore the focus from an EditText.
So I introduced a new class: the DefocusableScrollView, which inherits from the ScrollView.
The behavior is the same as a classic scrollView, but auto-refocus can be disabled through a public function.

**- Hardware keyboard key converter**
Despite this piece of code being scheduled not to change anytime soon, you may want to add support for more keys.
If you do so, please add the mapping so the android key code is sorted in the array.
For this purpose, a simple function *add(int androidKeycode, short LWJGLKeycode)* is at your disposal.
You also need to increase the array size of the android keycode array by one.

**- Gamepad reconfiguration**
Gamepad uses mappings internally *(in game/menus)*, so [partial button remapping could be easily supported](https://github.com/dolphin-emu/dolphin/blob/db5a78781f7df896b3c2e3d41f2ca26dfa5b36a1/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/InputBindingSetting.java).
Convenience functions are at your disposal to safely initialize members of a gamepadMapping.

**- Button setting layout**
The layout for settings of the ControlButton and its children the ControlDrawer and ControlSubButton is the same.
As such, options not used by one object have to be hidden upon inflation of the layout.

**- Flat button preference**
This preference has been removed from the codebase, as such new users are expected to use the flat style. :eyes:

**- getMcScale function**
This function now notifies the gamepad (if it exists) of a change of scale.

**- Tools class**
The DP --> PX and vice versa implementation has been tweaked and should need no further changes.

**- .gitignore**
It has been updated to hie folders generated by android studio.

# What's left to change ?
- ~~Fix *UNKNOWN* key appearing two times in the ControlButton settings~~
- ~~Fix the gamepad not triggering key modifiers such as *Alt*, *Shift*...~~
- The **touch and gamepad** layouts are a bit un-intuitive.
- Support for the 120Hz screens ?
- I don't like how it scrolls, even with the tweaking I did.
- Surely something else.

# Conclusion
oh, you reached the end ?
Read the article again I guess.

### CODE REVIEW

**Comment by mchnjt** [comment]
SO EPIK

**Comment by ghost** [comment]
> SO EPIK

YEAHH

**Comment by CriticalRange** [comment]
No conflict left let's gooooooo

**Comment by Zeyrox1090** [comment]
Pog

**Comment by WesleyVanNeck** [comment]
great job serpent

**Pull request merged**
