### PR TITLE
Feat[Turnip]: Support for A750,update to latest

### PR DESCRIPTION
**Pull request by Vera-Firefly**
Your Turnip Driver is so far behind, update this!

### CODE REVIEW

**Comment by Mathias-Boulay** [comment]
hmm, perhaps the driver should be updated on the fly by the CI instead ?

**Comment by Mathias-Boulay** [comment]
Trying to keep it up to date will balloon the repository size

**Comment by Vera-Firefly** [comment]
> hmm, perhaps the driver should be updated on the fly by the CI instead ?

This method is not feasible
And this is submitted to the Turnip driver of the official version 24.1.0
If you try to get the latest using a CI build, there is no guarantee that it will be stable and effective.

**Comment by Vera-Firefly** [comment]
The Turnip driver for this commit is built from https://gitlab.freedesktop.org/mesa/mesa/-/tree/mesa-24.0.4?ref_type=tags

**Comment by Vera-Firefly** [comment]
Use the official release, not the content in the test
I don't think it's a good choice to use what's in the test

**Comment by Vera-Firefly** [comment]
> Trying to keep it up to date will balloon the repository size

This does not take up much ...

**Comment by namtacs** [comment]
> > hmm, perhaps the driver should be updated on the fly by the CI instead ?
> 
> This method is not feasible

Just check for the stable version?

**Comment by Algiuxs** [comment]
> > Trying to keep it up to date will balloon the repository size
> 
> This does not take up much ...

He means commit history

**Pull request closed without merging**
