### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by khanhduytran0**

### CODE REVIEW

**Comment by GamingPad** [comment]
When i launch version the no log output was showing and auto back and show mobile menu.
Device specs:- 4/64gb 
Please help me i want to play pojav launcher
Discord id:- Gaming Pad#0001
Dm me

**Comment by khanhduytran0** [comment]
> When i launch version the no log output was showing and auto back and show mobile menu.
> Device specs:- 4/64gb
> Please help me i want to play pojav launcher
> Discord id:- Gaming Pad#0001
> Dm me

@GamingPad You can also report bug at https://github.com/PojavLauncherTeam/PojavLauncher/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D
(remember to fill in the template)

**Comment by OwzygZawg** [comment]
Why notifications for me? Lol

**Comment by Rafil123** [comment]
Pls Update Pojavlauncher Virgl fix bug Java Shader and fix Lag Pojavlauncher Virgl 150FPS

**Comment by Rafil123** [comment]
When is Poja Virgl Update please let me know because when I use the Sildurs Shader, how come the GoodRays disappear, the difference with Zink If Zink has GoodRays and Lensflare but if Virgl Why isn't there please Update Pojav Launcher Virgl to Virgl 3.9 so I can use Shader Java without any lag If my Vgpu gets 300FPS IF VIRGL IS ONLY 60FPS EVEN WHEN THE SETTINGS ARE STILL 60FPS IF VGPU TOUCH 300fps please on. make the same and also please fix all the bugs so that all the Java shaders I use are the same as in the original Java

**Comment by mchnjt** [comment]
stfu
fps ≠ shader compatibility

**Review by Rafil123 — COMMENTED** [review]
Pls Update POJAVLAUNCHER Virgl Render 4.3 Update to Virgl 3.9

**Pull request closed without merging**
