### PR TITLE
Minecraft java

### PR DESCRIPTION
**Pull request by ysnilhmprygoz**
@LegacyGamerHD

### CODE REVIEW

**Comment by ysnilhmprygoz** [comment]
@Axoloski

**Comment by ysnilhmprygoz** [comment]
@ysnilhmprygoz

**Comment by ysnilhmprygoz** [comment]
v3_openjdk

**Comment by ysnilhmprygoz** [comment]
@adaue1

**Comment by ysnilhmprygoz** [comment]
@khanhduytran0

**Comment by ysnilhmprygoz** [comment]
ysnilhmprygoz

**Comment by ysnilhmprygoz** [comment]
- [x] @khanhduytran#3252

**Comment by ysnilhmprygoz** [comment]
Minecraft java#3252

**Comment by ysnilhmprygoz** [comment]
Fix for offset selection view

**Comment by ysnilhmprygoz** [comment]
This reverts commit f966a15.

**Comment by ysnilhmprygoz** [comment]
Fix for offset selection view

**Comment by ysnilhmprygoz** [comment]
Nothing to preview

**Comment by mchnjt** [comment]
> Nothing to preview

Please learn on how to use github and open pull requests.

**Pull request closed without merging**
