### PR TITLE
Changelog Page Tweaks

### PR DESCRIPTION
**Pull request by mchnjt**
based

### CODE REVIEW

**Review by mchnjt — COMMENTED** [review]
Removed excess amount of h2's

**Review by khanhduytran0 — CHANGES_REQUESTED** [review]
> `<b>• <a href="https://pojavlauncherteam.github.io/">PojavLauncher Website`

Syntax goes brrrr :trollface:

**Comment by mchnjt** [comment]
based

**Comment by mchnjt** [comment]
grammar check 2 time

**Comment by mchnjt** [comment]
I hope it works properly

**Review by khanhduytran0 — APPROVED** [review]

**Pull request merged**
