### PR TITLE
Rename .github/workflows/android.yml to Android cl

### PR DESCRIPTION
**Pull request by Trollfacegamer**

### CODE REVIEW

**Comment by khanhduytran0** [comment]
@Trollfacegamer and so what does that do?

**Comment by khanhduytran0** [comment]
nice alt, @Trollfacegamer @trollfacegamer

**Comment by khanhduytran0** [comment]
nice alt, @Trollfacegamer @trollfacegaming @trollfacegaming75

**Comment by mchnjt** [comment]
nice pr

**Pull request closed without merging**
