### PR TITLE
feat(control): allow subbuttons of free orientation drawer change size

### PR DESCRIPTION
**Pull request by DreamOneX**
This pull request allows users to change the size of sub-buttons in freeform drawer buttons.

This problem was mentioned in #1938

### CODE REVIEW

**Comment by Mathias-Boulay** [comment]
Ngl, this was an intentional design decision when the feature was initially developed

**Comment by artdeell** [comment]
> Ngl, this was an intentional design decision when the feature was initially developed

i mean, sure, but it can be very much usable (especially with drawer auto-actuation)

**Comment by Mathias-Boulay** [comment]
Yeah, I have to say the free placement wasn't considered at first, so the PR makes sense.

You forgot to bump up the version number of the control schema. Despite the fact you didn't change it, this will forbid older versions to use a schema that makes use of this new feature

**Comment by artdeell** [comment]
Ah right, please do that, otherwise when loading a new layout on an old version it will roll back the size

**Comment by DreamOneX** [comment]
> Yeah, I have to say the free placement wasn't considered at first, so the PR makes sense.
> 
> You forgot to bump up the version number of the control schema. Despite the fact you didn't change it, this will forbid older versions to use a schema that makes use of this new feature

thanks for reminding !

I bumped up the version number, but I noticed that there is a comment on the 60th line of [`CustomControls.java`](https://github.com/PojavLauncherTeam/PojavLauncher/pull/4429/files#diff-6d2ae16eb89bd6dbe59d438f3ef6ddd1b35fd9dc976762c81f64ea9177adf76cL60), I don't quite understand its meaning, so I directly increased the number. should do so ?

**Comment by Mathias-Boulay** [comment]
LGTM, thank you for your PR (and following conventional commits guidelines)

**Review by Mathias-Boulay — APPROVED** [review]

**Pull request merged**
