### PR TITLE
UI revamp (v2)

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
Hey, it is me again, with another (although WAY BIGGER) pull request than before.
What does this one do ? A lot of things actually.

First of all, the UI v2 was remade from scratch with the help of the constraintLayout (and ditching away the TabLayout within the old iteration of this UI).
**This revamped version features:**
- A friendlier interface for the end user, with good visual sign to locate where you are within the interface
- More icons !
- A more easy way for the dev to maintain it [(The layout preview is near what you get from runtime)](https://user-images.githubusercontent.com/24864674/104066792-49699300-5202-11eb-9b59-37317eb21c15.png)

But the new layout isn't the only major change.
This pull request brings a new layout for selecting saved account that is easier to navigate in !
 
The UI v1 was removed, and as such, I removed the manager that was used to switch from the v1 to the v2.

**Miscellaneous:**
- All Gradle dependencies were updated, this brings bug fixes. On top of that, a dependency for the constraintLayout has been added

Here are two videos of how it looks/works now:
https://user-images.githubusercontent.com/24864674/104066424-b3ce0380-5201-11eb-9a98-a9aa55ee7548.mp4

https://user-images.githubusercontent.com/24864674/104066449-bcbed500-5201-11eb-9328-d566ba85b2de.mp4

### CODE REVIEW

**Comment by khanhduytran0** [comment]
This will affect V1 UI...
image

**Comment by khanhduytran0** [comment]
But may then set v2 UI as default?

**Comment by Mathias-Boulay** [comment]
> But may then set v2 UI as default?

Allow me to restate what I said in my pull request earlier: THE V1 HAS BEEN REMOVED.
Meaning the UI v2 is the only *(and the default)* UI from now on.

**Comment by khanhduytran0** [comment]
Ok.. so may add delete confirm dialog later?

**Comment by artdeell** [comment]
Yeah, delete dialog would be very cool

**Comment by Mathias-Boulay** [comment]
I can add it back now, it will be automatically included in this pull request.
I just have to get out of bed ^^'

**Comment by ghost** [comment]
Let's see

**Comment by Mathias-Boulay** [comment]
> Ok.. so may add delete confirm dialog later?

> Yeah, delete dialog would be very cool

Pushed a commit which restores the delete account dialog: 

https://user-images.githubusercontent.com/24864674/104087985-bf521680-5263-11eb-8816-b7ecf886bf82.mp4

**Pull request merged**
