### PR TITLE
Java16 test

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by khanhduytran0** [comment]
@nvidia837 are u @pojavtest?

**Comment by khanhduytran0** [comment]
wtf by java 16 test

**Comment by artdeell** [comment]
I guess. Why remove the workflow file though? There's no point

**Comment by khanhduytran0** [comment]
building pojav with java 16 doesn’t related, **it doesn’t let 1.17 run without da runtime**

**Review by khanhduytran0 — COMMENTED** [review]
And how did he even ignore the branch itself

**Comment by ghost** [comment]
I want to test if pojav can run on java16. completely or not

ในวันที่ พ. 7 ก.ค. 2021 16:17 น. Duy Tran Khanh ***@***.***>
เขียนว่า:

**Comment by khanhduytran0** [comment]
> I want to test if pojav can run on java16. completely or not ในวันที่ พ. 7 ก.ค. 2021 16:17 น. Duy Tran Khanh ***@***.***> เขียนว่า:
> […](#)

It doesn’t related. What you need is called as “runtime”. Follow this instead https://pojavlauncherteam.github.io/updates/117.html

**Pull request closed without merging**
